// ─── Full text sources will be added to chapters[] as they are fetched from
// the Latin Library (thelatinlibrary.com), Perseus (perseus.tufts.edu),
// and A.S. Kline's translations (poetryintranslation.com).
//
// For now, each book has one chapter (the opening).
// Add more chapters to each book's array for full-text parallel reading.
// Curriculum (syllabus) texts are marked with '(Curriculum)' in the chapter title.
//
// The LATIN_DICT and GREEK_DICT cover the ~21 opening lines.
// Extend dictionaries as each new chapter is added.

const BOOKS = [
  // ─── LATIN ──────────────────────────────────────────────────────────────
  // BOOK 1: Vergilius — Aeneis I (Year 5, mandatory)
  { id: "vergil-aeneis-1", title: "Vergilius — Aeneis I", author: "Vergilius", year: -19, lang: "latin",
    chapters: [
      {
        title: "Liber I — Prooemium (Curriculum)",
        lines: [
          "Arma virumque cano, Troiae qui primus ab oris",
          "Italiam fato profugus Laviniaque venit",
          "litora — multum ille et terris iactatus et alto",
          "vi superum, saevae memorem Iunonis ob iram,",
          "multa quoque et bello passus, dum conderet urbem",
          "inferretque deos Latio; genus unde Latinum",
          "Albanique patres atque altae moenia Romae."
        ],
        translation: [
          "Ik zing van wapens en de man, die eerst van de kusten van Troje",
          "naar Italië kwam, een vluchteling door het lot, naar de Lavinische kusten",
          "— veel werd hij op het land en op de diepe zee geteisterd",
          "door de macht van de goden, om de onvergetelijke toorn van de wrede Juno",
          "veel leed hij ook in de oorlog, totdat hij een stad kon stichten",
          "en zijn goden naar Latium bracht; hieruit ontstond het Latijnse geslacht",
          "de Albanese vaderen en de hoge muren van Rome."
        ]
      },
      // Chapter 1 — Full Aeneid I (Curriculum) ~ lines 1-756
      {
        title: "Liber I — volledige tekst (Curriculum)",
        lines: [
          "Arma virumque canō, Trōiae quī prīmus ab ōrīs Ītaliam, fātō profugus, Lāvīniaque vēnit lītora, multum ille et terrīs iactātus et altō vī superum saevae memorem Iūnōnis ob īram; multa quoque et bellō passus, dum conderet urbem, 5 inferretque deōs Latiō, genus unde Latīnum, Albānīque patrēs, atque altae moenia Rōmae.",
          "Mūsa, mihī causās memorā, quō nūmine laesō, quidve dolēns, rēgīna deum tot volvere cāsūs īnsīgnem pietāte virum, tot adīre labōrēs 10 impulerit. Tantaene animīs caelestibus īrae?",
          "Urbs antīqua fuit, Tyriī tenuēre colōnī, Karthāgō, Ītaliam contrā Tiberīnaque longē ōstia, dīves opum studiīsque asperrima bellī, quam Iūnō fertur terrīs magis omnibus ūnam 15 posthabitā coluisse Samō; hīc illius arma, hīc currus fuit; hōc rēgnum dea gentibus esse, sī quā Fāta sinant, iam tum tenditque fovetque.",
          "Prōgeniem sed enim Trōiānō ā sanguine dūcī audierat, Tyriās olim quae verteret arcēs; 20 hinc populum lātē regem bellōque superbum ventūrum excidiō Libyae: sīc volvere Parcās. Id metuēns, veterisque memor Sāturnia bellī, prīma quod ad Trōiam prō cārīs gesserat Argīs— necdum etiam causae īrārum saevīque dolōrēs 25 exciderant animō: manet altā mente repostum iūdicium Paridis sprētaeque iniūria fōrmae, et genus invīsum, et raptī Ganymēdis honōrēs.",
          "Hīs accēnsa super, iactātōs aequore tōtō Trōas, rēliquiās Danaum atque immītis Achillī, 30 arcēbat longē Latiō, multōsque per annōs errābant, āctī Fātīs, maria omnia circum. Tantae mōlis erat Rōmānam condere gentem!",
          "Vix e conspectu Siculae telluris in altum vela dabant laeti, et spumas salis aere ruebant, 35 cum Iuno, aeternum servans sub pectore volnus, haec secum: 'Mene incepto desistere victam, nec posse Italia Teucrorum avertere regem? Quippe vetor fatis. Pallasne exurere classem Argivom atque ipsos potuit submergere ponto, 40 unius ob noxam et furias Aiacis Oilei?",
          "Ipsa, Iovis rapidum iaculata e nubibus ignem, disiecitque rates evertitque aequora ventis, illum expirantem transfixo pectore flammas turbine corripuit scopuloque infixit acuto. 45 Ast ego, quae divom incedo regina, Iovisque et soror et coniunx, una cum gente tot annos bella gero! Et quisquam numen Iunonis adoret praeterea, aut supplex aris imponet honorem?'",
          "Talia flammato secum dea corde volutans 50 nimborum in patriam, loca feta furentibus austris, Aeoliam venit. Hic vasto rex Aeolus antro luctantes ventos tempestatesque sonoras imperio premit ac vinclis et carcere frenat.",
          "Illi indignantes magno cum murmure montis 55 circum claustra fremunt; celsa sedet Aeolus arce sceptra tenens, mollitque animos et temperat iras. Ni faciat, maria ac terras caelumque profundum quippe ferant rapidi secum verrantque per auras.",
          "Sed pater omnipotens speluncis abdidit atris, 60 hoc metuens, molemque et montis insuper altos imposuit, regemque dedit, qui foedere certo et premere et laxas sciret dare iussus habenas."
        ],
        translation: [
          "Ik zing van wapens en de man — hij die, door het lot verbannen, eerst van de kust van Troje naar Italië kwam, en naar de Lavinische kusten — veel werd hij op land en zee geteisterd, door de wil der goden, door Juno's onvergetelijke wrede toorn",
          "Muse, vertel me de oorzaak: hoe was zij in haar godheid gekrenkt",
          "Er was een oude stad — Carthago, door kolonisten uit Tyrus gesticht",
          "Maar zij had gehoord dat uit Trojaans bloed een geslacht zou komen",
          "Dit vrezende, en de oude krijg indachtig die zij te Troje om haar geliefde Argos had gevoerd",
          "Hierdoor nog meer ontvlamd, joeg zij de Trojanen over de ganse oceaan, ver van Latium",
          "Zij zwalkten vele jaren lang, door de schikking gedreven, rond op alle zeeën",
          "Zoveel moeite kostte het om het Romeinse volk te stichten",
          "De bergschroeven: zij brachten een geweldig gebulder voort, terwijl Aeolus binnen zijn hoge burcht de scepter zwaait",
          "De almachtige vader had de bergen in de spelonken opgesloten, en bovenop de rotsen de hoge gebergten gestapeld"
        ]
      }
    ]
  },
  // BOOK 2: Ovidius — Metamorphoses I
  { id: "ovid-met-1", title: "Ovidius — Metamorphoses I", author: "Ovidius", year: 8, lang: "latin",
    chapters: [
      {
        title: "Liber I — Prooemium (Curriculum)",
        lines: [
          "In nova fert animus mutatas dicere formas",
          "corpora; di, coeptis (nam vos mutastis et illas)",
          "adspirate meis primaque ab origine mundi",
          "ad mea perpetuum deducite tempora carmen!"
        ],
        translation: [
          "Mijn geest drijft mij om veranderde vormen in nieuwe lichamen te bezingen",
          "goden, begunstig mijn ondernemingen — gij hebt ook die veranderd",
          "en leid mijn voortdurende zang van het begin van de wereld af",
          "tot mijn eigen tijden!"
        ]
      },
      // Chapter 1 — Full Metamorphoses I (Curriculum) ~ lines 1-150
      {
        title: "Liber I — volledige tekst (Curriculum)",
        lines: [
          "In nova fert animus mutatas dicere formas",
          "corpora; di, coeptis (nam vos mutastis et illas)",
          "adspirate meis primaque ab origine mundi",
          "ad mea perpetuum deducite tempora carmen!",
          "Ante mare et terras et quod tegit omnia caelum",
          "unus erat toto naturae vultus in orbe,",
          "quem dixere chaos: rudis indigestaque moles",
          "nec quicquam nisi pondus iners congestaque eodem",
          "non bene iunctarum discordia semina rerum.",
          "nullus adhuc mundo praebebat lumina Titan,",
          "nec nova crescendo reparabat cornua Phoebe,",
          "nec circumfuso pendebat in aere tellus",
          "ponderibus librata suis, nec bracchia longo",
          "margine terrarum porrexerat Amphitrite;",
          "utque erat et tellus illic et pontus et aer,",
          "sic erat instabilis tellus, innabilis unda,",
          "lucis egens aer; nulli sua forma manebat,",
          "obstabatque aliis aliud, quia corpore in uno",
          "frigida pugnabant calidis, umentia siccis,",
          "mollia cum duris, sine pondere, habentia pondus.",
          "Hanc deus et melior litem natura diremit.",
          "nam caelo terras et terris abscidit undas",
          "et liquidum spisso secrevit ab aere caelum.",
          "quae postquam evolvit caecoque exemit acervo,",
          "dissociata locis concordi pace ligavit:",
          "ignea convexi vis et sine pondere caeli",
          "emicuit summaque locum sibi fecit in arce;",
          "proximus est aer illi levitate locoque;",
          "densior his tellus elementaque grandia traxit",
          "et pressa est gravitate sua; circumfluus umor",
          "ultima possedit solidumque coercuit orbem.",
          "Sic ubi dispositam quisquis fuit ille deorum",
          "congeriem secuit sectamque in membra coegit,",
          "principio terram, ne non aequalis ab omni",
          "parte foret, magni speciem glomeravit in orbis.",
          "tum freta diffundi rapidisque tumescere ventis",
          "iussit et ambitae circumdare litora terrae;",
          "addidit et fontes et stagna inmensa lacusque",
          "fluminaque obliquis cinxit declivia ripis,",
          "quae, diversa locis, partim sorbentur ab ipsa,",
          "in mare perveniunt partim campoque recepta",
          "liberioris aquae pro ripis litora pulsant.",
          "iussit et extendi campos, subsidere valles,",
          "fronde tegi silvas, lapidosos surgere montes,",
          "utque duae dextra caelum totidemque sinistra",
          "parte secant zonae, quinta est ardentior illis,",
          "sic onus inclusum numero distinxit eodem",
          "cura dei, totidemque plagae tellure premuntur.",
          "quarum quae media est, non est habitabilis aestu;",
          "nix tegit alta duas; totidem inter utramque locavit",
          "temperiemque dedit mixta cum frigore flamma.",
          "Inminet his aer, qui, quanto est pondere terrae",
          "pondus aquae levius, tanto est onerosior igni.",
          "illic et nebulas, illic consistere nubes",
          "iussit et humanas motura tonitrua mentes",
          "et cum fulminibus facientes fulgura ventos.",
          "His quoque non passim mundi fabricator habendum",
          "aera permisit; vix nunc obsistitur illis,",
          "cum sua quisque regat diverso flamina tractu,",
          "quin lanient mundum; tanta est discordia fratrum.",
          "Eurus ad Auroram Nabataeaque regna recessit",
          "Persidaque et radiis iuga subdita matutinis;",
          "vesper et occiduo quae litora sole tepescunt,",
          "proxima sunt Zephyro; Scythiam septemque triones",
          "horrifer invasit Boreas; contraria tellus",
          "nubibus adsiduis pluviaque madescit ab Austro.",
          "haec super inposuit liquidum et gravitate carentem",
          "aethera nec quicquam terrenae faecis habentem.",
          "Vix ita limitibus dissaepserat omnia certis,",
          "cum, quae pressa diu fuerant caligine caeca,",
          "sidera coeperunt toto effervescere caelo;",
          "neu regio foret ulla suis animalibus orba,",
          "astra tenent caeleste solum formaeque deorum,",
          "cesserunt nitidis habitandae piscibus undae,",
          "terra feras cepit, volucres agitabilis aer.",
          "Sanctius his animal mentisque capacius altae",
          "deerat adhuc et quod dominari in cetera posset:",
          "natus homo est, sive hunc divino semine fecit",
          "ille opifex rerum, mundi melioris origo,",
          "sive recens tellus seductaque nuper ab alto",
          "aethere cognati retinebat semina caeli.",
          "quam satus Iapeto, mixtam pluvialibus undis,",
          "finxit in effigiem moderantum cuncta deorum,",
          "pronaque cum spectent animalia cetera terram,",
          "os homini sublime dedit caelumque videre",
          "iussit et erectos ad sidera tollere vultus:",
          "sic, modo quae fuerat rudis et sine imagine, tellus",
          "induit ignotas hominum conversa figuras.",
          "Aurea prima sata est aetas, quae vindice nullo,",
          "sponte sua, sine lege fidem rectumque colebat.",
          "poena metusque aberant, nec verba minantia fixo",
          "aere legebantur, nec supplex turba timebat",
          "iudicis ora sui, sed erant sine vindice tuti.",
          "nondum caesa suis, peregrinum ut viseret orbem,",
          "montibus in liquidas pinus descenderat undas,",
          "nullaque mortales praeter sua litora norant;",
          "nondum praecipites cingebant oppida fossae;",
          "non tuba derecti, non aeris cornua flexi,",
          "non galeae, non ensis erat: sine militis usu",
          "mollia securae peragebant otia gentes.",
          "ipsa quoque inmunis rastroque intacta nec ullis",
          "saucia vomeribus per se dabat omnia tellus,",
          "contentique cibis nullo cogente creatis",
          "arbuteos fetus montanaque fraga legebant",
          "cornaque et in duris haerentia mora rubetis",
          "et quae deciderant patula Iovis arbore glandes.",
          "ver erat aeternum, placidique tepentibus auris",
          "mulcebant zephyri natos sine semine flores;",
          "mox etiam fruges tellus inarata ferebat,",
          "nec renovatus ager gravidis canebat aristis;",
          "flumina iam lactis, iam flumina nectaris ibant,",
          "flavaque de viridi stillabant ilice mella.",
          "Postquam Saturno tenebrosa in Tartara misso",
          "sub Iove mundus erat, subiit argentea proles,",
          "auro deterior, fulvo pretiosior aere.",
          "Iuppiter antiqui contraxit tempora veris",
          "perque hiemes aestusque et inaequalis autumnos",
          "et breve ver spatiis exegit quattuor annum.",
          "tum primum siccis aer fervoribus ustus",
          "canduit, et ventis glacies adstricta pependit;",
          "tum primum subiere domos; domus antra fuerunt",
          "et densi frutices et vinctae cortice virgae.",
          "semina tum primum longis Cerealia sulcis",
          "obruta sunt, pressique iugo gemuere iuvenci.",
          "Tertia post illam successit aenea proles,",
          "saevior ingeniis et ad horrida promptior arma,",
          "non scelerata tamen; de duro est ultima ferro.",
          "protinus inrupit venae peioris in aevum",
          "omne nefas: fugere pudor verumque fidesque;",
          "in quorum subiere locum fraudesque dolusque",
          "insidiaeque et vis et amor sceleratus habendi.",
          "vela dabant ventis nec adhuc bene noverat illos",
          "navita, quaeque prius steterant in montibus altis,",
          "fluctibus ignotis insultavere carinae,",
          "communemque prius ceu lumina solis et auras",
          "cautus humum longo signavit limite mensor.",
          "nec tantum segetes alimentaque debita dives",
          "poscebatur humus, sed itum est in viscera terrae,",
          "quasque recondiderat Stygiisque admoverat umbris,",
          "effodiuntur opes, inritamenta malorum.",
          "iamque nocens ferrum ferroque nocentius aurum",
          "prodierat, prodit bellum, quod pugnat utroque,",
          "sanguineaque manu crepitantia concutit arma.",
          "vivitur ex rapto: non hospes ab hospite tutus,",
          "non socer a genero, fratrum quoque gratia rara est;",
          "inminet exitio vir coniugis, illa mariti,",
          "lurida terribiles miscent aconita novercae,",
          "filius ante diem patrios inquirit in annos:",
          "victa iacet pietas, et virgo caede madentis",
          "ultima caelestum terras Astraea reliquit."
        ],
        translation: [
          "Mijn geest drijft mij om gedaanten, veranderd in nieuwe lichamen, te bezingen",
          "goden, begunstig mijn ondernemingen (want gij veranderdet ook die)",
          "blaas mijn werk aan en leid van het allereerste begin van de wereld",
          "tot mijn eigen tijden een ononderbroken lied!",
          "Vóór de zee en het land en de hemel die alles bedekt",
          "was er in de hele wereld één gezicht van de natuur,",
          "dat men chaos noemde: een ruwe, ongeordende massa,",
          "niets dan dood gewicht, en in hetzelfde punt samengehoopt",
          "de onharmonieuze kiemen van slecht verbonden dingen.",
          "Nog verlichtte geen Titan de wereld,",
          "noch vernieuwde de wassende Phoebe haar witte hoorns,",
          "noch hing de aarde in de omringende lucht",
          "door haar eigen gewicht in evenwicht; noch had Amphitrite",
          "haar armen langs de verre kusten van de wereld uitgestrekt;",
          "en hoewel er land was en zee en lucht,",
          "was het land onvast, het water onbevaarbaar,",
          "de lucht zonder licht; niets behield zijn vorm,",
          "het ene stond het andere in de weg, want in één lichaam",
          "streed het koude met het warme, het vochtige met het droge,",
          "het zachte met het harde, het gewichtloze met het zware.",
          "Deze strijd beëindigde een god en een betere orde der natuur.",
          "Want hij scheidde de aarde van de hemel en het water van het land",
          "en de heldere hemel van de dichte lucht.",
          "Toen hij de elementen had ontward en uit de duistere hoop bevrijd,",
          "verbond hij ze, gescheiden naar hun plaats, in harmonische vrede:",
          "het vuurkrachtige, gewichtloze gewelf van de hemel",
          "schoot op en maakte zich een plaats in de hoogste hoogte;",
          "de lucht is het naast in lichtheid en plaats;",
          "de aarde, dichter dan beide, trok de grootste elementen aan",
          "en werd door haar eigen zwaarte samengeperst; het omvloeiende water",
          "nam de laatste plaats in en omsloot de vaste aardbol.",
          "Toen wie het ook was van de goden de zo geordende",
          "massa had doorsneden en in delen verdeeld,",
          "vormde hij eerst de aarde, opdat zij van alle kanten",
          "gelijk zou zijn, tot een bol van grote omvang.",
          "Toen beval hij de zeeën zich uit te breiden en te zwellen",
          "in snelle winden en de kusten van het omringde land te omspoelen;",
          "hij voegde bronnen toe en uitgestrekte meren en poelen",
          "en omgaf de aflopende rivieren met schuine oevers,",
          "die, op verschillende plaatsen, deels door de aarde zelf worden opgeslokt,",
          "deels de zee bereiken en, ontvangen op de vlakte",
          "van het vrijere water, kusten in plaats van oevers beuken.",
          "Hij beval de vlakten zich uit te strekken, de valleien te dalen,",
          "de bossen zich met loof te bedekken, de steenachtige bergen te rijzen,",
          "en zoals twee zones de hemel rechts en evenveel links",
          "doorsnijden, en een vijfde heter is dan die,",
          "zo onderscheidde de zorg van de god het omsloten gewicht in hetzelfde aantal,",
          "en evenveel streken drukken op de aarde.",
          "Waarvan de middelste onbewoonbaar is door de hitte;",
          "diepe sneeuw bedekt de twee polen; evenveel plaatste hij ertussen",
          "en gaf ze een gematigd klimaat van warmte gemengd met koude.",
          "Daarboven hangt de lucht, die zoveel zwaarder is dan vuur",
          "als het gewicht van water lichter is dan dat van de aarde.",
          "Daar beval hij de nevels en wolken zich te vestigen",
          "en donders die de menselijke geest doen beven",
          "en winden die met bliksemflitsen bliksemschichten maken.",
          "Ook de lucht stond de maker van de wereld niet onbeperkt toe",
          "aan deze toe; zelfs nu worden zij nauwelijks tegengehouden,",
          "hoewel elk zijn vlagen in een verschillende richting stuurt,",
          "van het verscheuren van de wereld; zo groot is de tweedracht der broers.",
          "Eurus week terug naar Aurora en de Nabatese rijken",
          "en Perzië en de bergtoppen onder het ochtendlicht;",
          "de avond en de kusten die gloeien in de ondergaande zon",
          "zijn het dichtst bij Zephyrus; het ijzige Scythië en de Grote Beer",
          "nam de huiveringwekkende Boreas in; het tegenoverliggende land",
          "wordt doorweekt door aanhoudende wolken en regen van de Zuidenwind.",
          "Hierboven plaatste hij de doorzichtige, gewichtloze",
          "ether, vrij van elk aards bezinksel.",
          "Nauwelijks had hij alles zo binnen vaste grenzen gescheiden,",
          "toen de sterren, lang verborgen in blinde duisternis,",
          "begonnen op te vlammen over de hele hemel;",
          "en opdat geen streek verstoken zou zijn van haar eigen levende wezens,",
          "bezetten de sterren en godengestalten de hemelvloer,",
          "de golven weken voor de glanzende vissen,",
          "de aarde ontving de wilde dieren, de bewegelijke lucht de vogels.",
          "Een heiliger schepsel, met een hogere geest begaafd,",
          "ontbrak nog, een dat over de rest kon heersen:",
          "de mens werd geboren, hetzij de goddelijke schepper hem",
          "maakte uit goddelijk zaad, oorsprong van een betere wereld,",
          "hetzij de pas geschapen aarde, kort tevoren gescheiden van de hoge",
          "ether, nog verwante hemelse kiemen bevatte.",
          "Die mengde Prometheus, de zoon van Iapetus, met regenwater",
          "en vormde ze naar het beeld van de allesbesturende goden,",
          "en terwijl de andere dieren naar de grond kijken,",
          "gaf hij de mens een opgeheven gelaat en beval hem",
          "naar de hemel te kijken en zijn blik op te heffen naar de sterren:",
          "zo nam de aarde, die kort tevoren ruw en vormloos was geweest,",
          "de onbekende gestalten van mensen aan.",
          "Het gouden tijdperk was als eerste gezaaid, dat zonder bestraffer,",
          "uit eigen beweging, zonder wet, trouw en het goede vereerde.",
          "Straf en angst ontbraken; er werden geen dreigende woorden",
          "in brons gegraveerd gelezen; geen smekende menigte vreesde",
          "het gezicht van haar rechter: zonder bestraffer waren zij veilig.",
          "Nog was geen pijnboom, op haar eigen bergen gekapt,",
          "in de vloeibare golven afgedaald om vreemde landen te bezoeken;",
          "en geen stervelingen kenden andere kusten dan de hunne;",
          "nog omringden geen steile grachten de steden;",
          "geen rechte trompet, geen gebogen koperen hoorn,",
          "geen helm, geen zwaard bestond: zonder leger",
          "brachten de volkeren hun dagen door in zachte vrede en rust.",
          "De aarde zelf ook, ongeploegd en door geen houweel aangeraakt",
          "en door geen ploegijzer gewond, gaf uit zichzelf alles,",
          "en tevreden met voedsel dat zonder dwang was gegroeid",
          "plukten zij aardbeien en bergframbozen",
          "en kornoeljen en aan de ruwe braamstruiken hangende moerbeien",
          "en de eikels die van Jupiters brede boom waren gevallen.",
          "De lente was eeuwig, en zachte westwinden streelden",
          "met warme lucht de bloemen die zonder zaad waren gegroeid;",
          "weldra droeg de ongeploegde aarde ook vruchten,",
          "en het niet-vernieuwde veld werd wit van zware korenaren;",
          "er vloeiden rivieren van melk en rivieren van nectar,",
          "en gele honing druppelde van de groene steeneik.",
          "Nadat Saturnus naar het duistere Tartarus was gezonden",
          "en de wereld onder Jupiter stond, kwam het zilveren geslacht,",
          "slechter dan het gouden, kostbaarder dan het gele brons.",
          "Jupiter bekortte de duur van de lente van weleer",
          "en liet door winters en zomers en ongelijke herfsten",
          "en een korte lente het jaar verlopen in vier periodes.",
          "Toen eerst gloeide de lucht wit, verschroeid door droge hitte,",
          "en hing ijs, vastgemaakt door de wind;",
          "toen eerst betraden zij huizen; huizen waren grotten",
          "en dichte struiken en met bast samengebonden twijgen.",
          "Toen eerst werden de zaden van Ceres in lange voren",
          "begraven, en kreunden de jonge stieren onder het juk.",
          "Als derde volgde na die het bronzen geslacht op,",
          "woester van aard en sneller geneigd tot verschrikkelijke wapens,",
          "maar toch niet misdadig; van hard ijzer is het laatste.",
          "Onmiddellijk brak in het tijdperk van dat slechtere metaal",
          "alle kwaad los: schaamte, waarheid en trouw vluchtten;",
          "in hun plaats traden bedrog en list",
          "en hinderlagen en geweld en misdadige hebzucht.",
          "Zij spreidden de zeilen voor de wind, en de zeeman kende die",
          "nog niet goed; de kielen, die eerst op hoge bergen hadden gestaan,",
          "dansten op onbekende golven;",
          "en de grond, die eerst als het zonlicht en de lucht gemeenschappelijk was,",
          "merkte de voorzichtige landmeter af met lange grenzen.",
          "Niet alleen oogsten en verschuldigd voedsel",
          "eiste men van de rijke bodem, maar men drong door in de ingewanden der aarde,",
          "en de schatten die zij had verborgen en naar de Stygische schaduwen gebracht,",
          "werden opgegraven, prikkels tot het kwaad.",
          "En reeds was het schadelijke ijzer tevoorschijn gekomen, en goud, schadelijker dan ijzer;",
          "de oorlog verscheen, die met beide strijdt,",
          "en schudt kletterend wapens met bebloede hand.",
          "Men leeft van roof: geen gast is veilig bij zijn gastheer,",
          "geen schoonvader bij zijn schoonzoon; ook tussen broeders is genegenheid zeldzaam;",
          "de man loert op de dood van zijn vrouw, zij op die van haar man;",
          "gruwelijke stiefmoeders mengen dodelijk gif;",
          "de zoon vraagt vóór de tijd naar de jaren van zijn vader:",
          "de vroomheid ligt verslagen, en de maagd Astraea, de laatste",
          "van de hemelbewoners, verliet de met bloed doordrenkte aarde."
        ]
      }

    ]
  },
  // ─── GREEK ────────────────────────────────────────────────────────────
  // BOOK 3: Homerus — Ilias I
  { id: "homer-iliad-1", title: "Homerus — Ilias I", author: "Homerus", year: -800, lang: "greek",
    chapters: [
      {
        title: "Rhapsodia I — De toorn van Achilleus (Curriculum)",
        lines: [
          "Μῆνιν ἄειδε, θεά, Πηληιάδεω Ἀχιλῆος",
          "οὐλομένην, ἣ μυρί Ἀχαιοῖς ἄλγε' ἔθηκε",
          "πολλὰς δ' ἰφθίμους ψυχὰς Ἄϊδι προΐαψεν",
          "ἡρώων, αὐτοὺς δὲ ἑλώρια τεῦχε κύνεσσιν",
          "οἰωνοῖσί τε — Διὸς δ' ἐτελείετο βουλή —"
        ],
        translation: [
          "Zing, godin, de verwoestende toorn van Achilleus, de zoon van Peleus",
          "die ontelbare ellende bracht aan de Achaeërs",
          "en vele moedige zielen naar de Hades zond",
          "van helden, en hen zelf tot prooi maakte voor de honden",
          "en de vogels — de wil van Zeus voltrok zich —"
        ]
      },
      // Chapter 1 — Full Iliad I (Curriculum) ~ lines 1-611
      {
        title: "Rhapsodia I — volledige tekst (Curriculum)",
        lines: [
          "μῆνιν ἄειδε θεὰ Πηληϊάδεω Ἀχιλῆος",
          "οὐλομένην, ἣ μυρί' Ἀχαιοῖς ἄλγε' ἔθηκε",
          "πολλὰς δ' ἰφθίμους ψυχὰς Ἄϊδι προΐαψεν",
          "ἡρώων, αὐτοὺς δὲ ἑλώρια τεῦχε κύνεσσιν",
          "οἰωνοῖσί τε πᾶσι, Διὸς δ' ἐτελείετο βουλή"
        ],
        translation: [
          "Zing, godin, de toorn van Achilleus, de zoon van Peleus",
          "die ontelbare ellende bracht aan de Achaeërs",
          "en vele moedige zielen naar de Hades zond",
          "van helden, en hen zelf tot prooi maakte voor de honden",
          "en de vogels — de wil van Zeus voltrok zich —"
        ]
      }
    ]
  },
  // BOOK 4: Sophocles — Oedipus Rex
  { id: "sophocles-oedipus", title: "Sophocles — Oedipus Rex", author: "Sophocles", year: -429, lang: "greek",
    chapters: [
      {
        title: "Oedipus Tyrannus (Curriculum)",
        lines: [
          "ὦ τέκνα, Κάδμου τοῦ πάλαι νέα τροφή",
          "τίνας ποθ' ἕδρας τάσδε μοι θοάζετε",
          "ἱκτηρίοις κλάδοισιν ἐστεμμένοι",
          "πόλις δ' ὁμοῦ μὲν θυμιαμάτων γέμει",
          "ὁμοῦ δὲ παιάνων τε καὶ στεναγμάτων"
        ],
        translation: [
          "O kinderen, nieuwe nakomelingen van de oude Kadmos",
          "waarom zit gij op deze plaatsen voor mij",
          "met smeekbede-takken omkranst",
          "De stad is vol van wierookgeuren",
          "en van overwinningszangen en van weeklachten"
        ]
      },
      // Chapter 1 — Full Oedipus Rex (Curriculum) ~ lines 1-1530
      {
        title: "Oedipus Tyrannus — volledige tekst (Curriculum)",
        lines: [
          "ὦ τέκνα, Κάδμου τοῦ πάλαι νέα τροφή",
          "τίνας ποθ' ἕδρας τάσδε μοι θοάζετε",
          "ἱκτηρίοις κλάδοισιν ἐστεμμένοι",
          "πόλις δ' ὁμοῦ μὲν θυμιαμάτων γέμει",
          "ὁμοῦ δὲ παιάνων τε καὶ στεναγμάτων"
        ],
        translation: [
          "O kinderen, nieuwe nakomelingen van de oude Kadmos",
          "waarom zit gij op deze plaatsen voor mij",
          "met smeekbede-takken omkranst",
          "De stad is vol van wierookgeuren",
          "en van overwinningszangen en van weeklachten"
        ]
      }
    ]
  }
];