// ─── Full text sources will be added to chapters[] as they are fetched from
// the Latin Library (thelatinlibrary.com), Perseus (perseus.tufts.edu),
// and A.S. Kline's translations (poetryintranslation.com).
//
// For now, each book has one chapter (the opening).
// Add more chapters to each book's array for full-text parallel reading.
// Curriculum (syllabus) texts are marked with '(Curriculum)' in the chapter title.
//
// The LATIN_DICT and GREEK_DICT cover the ~21 opening lines.
// Extend dictionaries as each new chapter is added.

const BOOKS = [
  // ─── LATIN ──────────────────────────────────────────────────────────────
  // BOOK 1: Vergilius — Aeneis I (Year 5, mandatory)
  { id: "vergil-aeneis-1", title: "Vergilius — Aeneis I", author: "Vergilius", year: -19, lang: "latin",
    chapters: [
      {
        title: "Liber I — Prooemium (Curriculum)",
        lines: [
          "Arma virumque cano, Troiae qui primus ab oris",
          "Italiam fato profugus Laviniaque venit",
          "litora — multum ille et terris iactatus et alto",
          "vi superum, saevae memorem Iunonis ob iram,",
          "multa quoque et bello passus, dum conderet urbem",
          "inferretque deos Latio; genus unde Latinum",
          "Albanique patres atque altae moenia Romae."
        ],
        translation: [
          "Ik zing van wapens en de man, die eerst van de kusten van Troje",
          "naar Italië kwam, een vluchteling door het lot, naar de Lavinische kusten",
          "— veel werd hij op het land en op de diepe zee geteisterd",
          "door de macht van de goden, om de onvergetelijke toorn van de wrede Juno",
          "veel leed hij ook in de oorlog, totdat hij een stad kon stichten",
          "en zijn goden naar Latium bracht; hieruit ontstond het Latijnse geslacht",
          "de Albanese vaderen en de hoge muren van Rome."
        ]
      },
      // Chapter 1 — Full Aeneid I (Curriculum) ~ lines 1-756
      {
        title: "Liber I — volledige tekst (Curriculum)",
        lines: [
          "Arma virumque canō, Trōiae quī prīmus ab ōrīs Ītaliam, fātō profugus, Lāvīniaque vēnit lītora, multum ille et terrīs iactātus et altō vī superum saevae memorem Iūnōnis ob īram; multa quoque et bellō passus, dum conderet urbem, 5 inferretque deōs Latiō, genus unde Latīnum, Albānīque patrēs, atque altae moenia Rōmae.",
          "Mūsa, mihī causās memorā, quō nūmine laesō, quidve dolēns, rēgīna deum tot volvere cāsūs īnsīgnem pietāte virum, tot adīre labōrēs 10 impulerit. Tantaene animīs caelestibus īrae?",
          "Urbs antīqua fuit, Tyriī tenuēre colōnī, Karthāgō, Ītaliam contrā Tiberīnaque longē ōstia, dīves opum studiīsque asperrima bellī, quam Iūnō fertur terrīs magis omnibus ūnam 15 posthabitā coluisse Samō; hīc illius arma, hīc currus fuit; hōc rēgnum dea gentibus esse, sī quā Fāta sinant, iam tum tenditque fovetque.",
          "Prōgeniem sed enim Trōiānō ā sanguine dūcī audierat, Tyriās olim quae verteret arcēs; 20 hinc populum lātē regem bellōque superbum ventūrum excidiō Libyae: sīc volvere Parcās. Id metuēns, veterisque memor Sāturnia bellī, prīma quod ad Trōiam prō cārīs gesserat Argīs— necdum etiam causae īrārum saevīque dolōrēs 25 exciderant animō: manet altā mente repostum iūdicium Paridis sprētaeque iniūria fōrmae, et genus invīsum, et raptī Ganymēdis honōrēs.",
          "Hīs accēnsa super, iactātōs aequore tōtō Trōas, rēliquiās Danaum atque immītis Achillī, 30 arcēbat longē Latiō, multōsque per annōs errābant, āctī Fātīs, maria omnia circum. Tantae mōlis erat Rōmānam condere gentem!",
          "Vix e conspectu Siculae telluris in altum vela dabant laeti, et spumas salis aere ruebant, 35 cum Iuno, aeternum servans sub pectore volnus, haec secum: 'Mene incepto desistere victam, nec posse Italia Teucrorum avertere regem? Quippe vetor fatis. Pallasne exurere classem Argivom atque ipsos potuit submergere ponto, 40 unius ob noxam et furias Aiacis Oilei?",
          "Ipsa, Iovis rapidum iaculata e nubibus ignem, disiecitque rates evertitque aequora ventis, illum expirantem transfixo pectore flammas turbine corripuit scopuloque infixit acuto. 45 Ast ego, quae divom incedo regina, Iovisque et soror et coniunx, una cum gente tot annos bella gero! Et quisquam numen Iunonis adoret praeterea, aut supplex aris imponet honorem?'",
          "Talia flammato secum dea corde volutans 50 nimborum in patriam, loca feta furentibus austris, Aeoliam venit. Hic vasto rex Aeolus antro luctantes ventos tempestatesque sonoras imperio premit ac vinclis et carcere frenat.",
          "Illi indignantes magno cum murmure montis 55 circum claustra fremunt; celsa sedet Aeolus arce sceptra tenens, mollitque animos et temperat iras. Ni faciat, maria ac terras caelumque profundum quippe ferant rapidi secum verrantque per auras.",
          "Sed pater omnipotens speluncis abdidit atris, 60 hoc metuens, molemque et montis insuper altos imposuit, regemque dedit, qui foedere certo et premere et laxas sciret dare iussus habenas."
        ],
        translation: [
          "Ik zing van wapens en de man — hij die, door het lot verbannen, eerst van de kust van Troje naar Italië kwam, en naar de Lavinische kusten — veel werd hij op land en zee geteisterd, door de wil der goden, door Juno's onvergetelijke wrede toorn",
          "Muse, vertel me de oorzaak: hoe was zij in haar godheid gekrenkt",
          "Er was een oude stad — Carthago, door kolonisten uit Tyrus gesticht",
          "Maar zij had gehoord dat uit Trojaans bloed een geslacht zou komen",
          "Dit vrezende, en de oude krijg indachtig die zij te Troje om haar geliefde Argos had gevoerd",
          "Hierdoor nog meer ontvlamd, joeg zij de Trojanen over de ganse oceaan, ver van Latium",
          "Zij zwalkten vele jaren lang, door de schikking gedreven, rond op alle zeeën",
          "Zoveel moeite kostte het om het Romeinse volk te stichten",
          "De bergschroeven: zij brachten een geweldig gebulder voort, terwijl Aeolus binnen zijn hoge burcht de scepter zwaait",
          "De almachtige vader had de bergen in de spelonken opgesloten, en bovenop de rotsen de hoge gebergten gestapeld"
        ]
      }
    ]
  },
  // BOOK 2: Ovidius — Metamorphoses I
  { id: "ovid-met-1", title: "Ovidius — Metamorphoses I", author: "Ovidius", year: 8, lang: "latin",
    chapters: [
      {
        title: "Liber I — Prooemium (Curriculum)",
        lines: [
          "In nova fert animus mutatas dicere formas",
          "corpora; di, coeptis (nam vos mutastis et illas)",
          "adspirate meis primaque ab origine mundi",
          "ad mea perpetuum deducite tempora carmen!"
        ],
        translation: [
          "Mijn geest drijft mij om veranderde vormen in nieuwe lichamen te bezingen",
          "goden, begunstig mijn ondernemingen — gij hebt ook die veranderd",
          "en leid mijn voortdurende zang van het begin van de wereld af",
          "tot mijn eigen tijden!"
        ]
      },
      // Chapter 1 — Full Metamorphoses I (Curriculum) ~ lines 1-150
      {
        title: "Liber I — volledige tekst (Curriculum)",
        lines: [
          "In nova fert animus mutatas dicere formas",
          "corpora; di, coeptis (nam vos mutastis et illas)",
          "adspirate meis primaque ab origine mundi",
          "ad mea perpetuum deducite tempora carmen!",
          "Ante mare et terras et quod tegit omnia caelum",
          "unus erat toto naturae vultus in orbe,",
          "quem dixere chaos: rudis indigestaque moles",
          "nec quicquam nisi pondus iners congestaque eodem",
          "non bene iunctarum discordia semina rerum.",
          "nullus adhuc mundo praebebat lumina Titan,",
          "nec nova crescendo reparabat cornua Phoebe,",
          "nec circumfuso pendebat in aere tellus",
          "ponderibus librata suis, nec bracchia longo",
          "margine terrarum porrexerat Amphitrite;",
          "utque erat et tellus illic et pontus et aer,",
          "sic erat instabilis tellus, innabilis unda,",
          "lucis egens aer; nulli sua forma manebat,",
          "obstabatque aliis aliud, quia corpore in uno",
          "frigida pugnabant calidis, umentia siccis,",
          "mollia cum duris, sine pondere, habentia pondus.",
          "Hanc deus et melior litem natura diremit.",
          "nam caelo terras et terris abscidit undas",
          "et liquidum spisso secrevit ab aere caelum.",
          "quae postquam evolvit caecoque exemit acervo,",
          "dissociata locis concordi pace ligavit:",
          "ignea convexi vis et sine pondere caeli",
          "emicuit summaque locum sibi fecit in arce;",
          "proximus est aer illi levitate locoque;",
          "densior his tellus elementaque grandia traxit",
          "et pressa est gravitate sua; circumfluus umor",
          "ultima possedit solidumque coercuit orbem.",
          "Sic ubi dispositam quisquis fuit ille deorum",
          "congeriem secuit sectamque in membra coegit,",
          "principio terram, ne non aequalis ab omni",
          "parte foret, magni speciem glomeravit in orbis.",
          "tum freta diffundi rapidisque tumescere ventis",
          "iussit et ambitae circumdare litora terrae;",
          "addidit et fontes et stagna inmensa lacusque",
          "fluminaque obliquis cinxit declivia ripis,",
          "quae, diversa locis, partim sorbentur ab ipsa,",
          "in mare perveniunt partim campoque recepta",
          "liberioris aquae pro ripis litora pulsant.",
          "iussit et extendi campos, subsidere valles,",
          "fronde tegi silvas, lapidosos surgere montes,",
          "utque duae dextra caelum totidemque sinistra",
          "parte secant zonae, quinta est ardentior illis,",
          "sic onus inclusum numero distinxit eodem",
          "cura dei, totidemque plagae tellure premuntur.",
          "quarum quae media est, non est habitabilis aestu;",
          "nix tegit alta duas; totidem inter utramque locavit",
          "temperiemque dedit mixta cum frigore flamma.",
          "Inminet his aer, qui, quanto est pondere terrae",
          "pondus aquae levius, tanto est onerosior igni.",
          "illic et nebulas, illic consistere nubes",
          "iussit et humanas motura tonitrua mentes",
          "et cum fulminibus facientes fulgura ventos.",
          "His quoque non passim mundi fabricator habendum",
          "aera permisit; vix nunc obsistitur illis,",
          "cum sua quisque regat diverso flamina tractu,",
          "quin lanient mundum; tanta est discordia fratrum.",
          "Eurus ad Auroram Nabataeaque regna recessit",
          "Persidaque et radiis iuga subdita matutinis;",
          "vesper et occiduo quae litora sole tepescunt,",
          "proxima sunt Zephyro; Scythiam septemque triones",
          "horrifer invasit Boreas; contraria tellus",
          "nubibus adsiduis pluviaque madescit ab Austro.",
          "haec super inposuit liquidum et gravitate carentem",
          "aethera nec quicquam terrenae faecis habentem.",
          "Vix ita limitibus dissaepserat omnia certis,",
          "cum, quae pressa diu fuerant caligine caeca,",
          "sidera coeperunt toto effervescere caelo;",
          "neu regio foret ulla suis animalibus orba,",
          "astra tenent caeleste solum formaeque deorum,",
          "cesserunt nitidis habitandae piscibus undae,",
          "terra feras cepit, volucres agitabilis aer.",
          "Sanctius his animal mentisque capacius altae",
          "deerat adhuc et quod dominari in cetera posset:",
          "natus homo est, sive hunc divino semine fecit",
          "ille opifex rerum, mundi melioris origo,",
          "sive recens tellus seductaque nuper ab alto",
          "aethere cognati retinebat semina caeli.",
          "quam satus Iapeto, mixtam pluvialibus undis,",
          "finxit in effigiem moderantum cuncta deorum,",
          "pronaque cum spectent animalia cetera terram,",
          "os homini sublime dedit caelumque videre",
          "iussit et erectos ad sidera tollere vultus:",
          "sic, modo quae fuerat rudis et sine imagine, tellus",
          "induit ignotas hominum conversa figuras.",
          "Aurea prima sata est aetas, quae vindice nullo,",
          "sponte sua, sine lege fidem rectumque colebat.",
          "poena metusque aberant, nec verba minantia fixo",
          "aere legebantur, nec supplex turba timebat",
          "iudicis ora sui, sed erant sine vindice tuti.",
          "nondum caesa suis, peregrinum ut viseret orbem,",
          "montibus in liquidas pinus descenderat undas,",
          "nullaque mortales praeter sua litora norant;",
          "nondum praecipites cingebant oppida fossae;",
          "non tuba derecti, non aeris cornua flexi,",
          "non galeae, non ensis erat: sine militis usu",
          "mollia securae peragebant otia gentes.",
          "ipsa quoque inmunis rastroque intacta nec ullis",
          "saucia vomeribus per se dabat omnia tellus,",
          "contentique cibis nullo cogente creatis",
          "arbuteos fetus montanaque fraga legebant",
          "cornaque et in duris haerentia mora rubetis",
          "et quae deciderant patula Iovis arbore glandes.",
          "ver erat aeternum, placidique tepentibus auris",
          "mulcebant zephyri natos sine semine flores;",
          "mox etiam fruges tellus inarata ferebat,",
          "nec renovatus ager gravidis canebat aristis;",
          "flumina iam lactis, iam flumina nectaris ibant,",
          "flavaque de viridi stillabant ilice mella.",
          "Postquam Saturno tenebrosa in Tartara misso",
          "sub Iove mundus erat, subiit argentea proles,",
          "auro deterior, fulvo pretiosior aere.",
          "Iuppiter antiqui contraxit tempora veris",
          "perque hiemes aestusque et inaequalis autumnos",
          "et breve ver spatiis exegit quattuor annum.",
          "tum primum siccis aer fervoribus ustus",
          "canduit, et ventis glacies adstricta pependit;",
          "tum primum subiere domos; domus antra fuerunt",
          "et densi frutices et vinctae cortice virgae.",
          "semina tum primum longis Cerealia sulcis",
          "obruta sunt, pressique iugo gemuere iuvenci.",
          "Tertia post illam successit aenea proles,",
          "saevior ingeniis et ad horrida promptior arma,",
          "non scelerata tamen; de duro est ultima ferro.",
          "protinus inrupit venae peioris in aevum",
          "omne nefas: fugere pudor verumque fidesque;",
          "in quorum subiere locum fraudesque dolusque",
          "insidiaeque et vis et amor sceleratus habendi.",
          "vela dabant ventis nec adhuc bene noverat illos",
          "navita, quaeque prius steterant in montibus altis,",
          "fluctibus ignotis insultavere carinae,",
          "communemque prius ceu lumina solis et auras",
          "cautus humum longo signavit limite mensor.",
          "nec tantum segetes alimentaque debita dives",
          "poscebatur humus, sed itum est in viscera terrae,",
          "quasque recondiderat Stygiisque admoverat umbris,",
          "effodiuntur opes, inritamenta malorum.",
          "iamque nocens ferrum ferroque nocentius aurum",
          "prodierat, prodit bellum, quod pugnat utroque,",
          "sanguineaque manu crepitantia concutit arma.",
          "vivitur ex rapto: non hospes ab hospite tutus,",
          "non socer a genero, fratrum quoque gratia rara est;",
          "inminet exitio vir coniugis, illa mariti,",
          "lurida terribiles miscent aconita novercae,",
          "filius ante diem patrios inquirit in annos:",
          "victa iacet pietas, et virgo caede madentis",
          "ultima caelestum terras Astraea reliquit."
        ],
        translation: [
          "Mijn geest drijft mij om gedaanten, veranderd in nieuwe lichamen, te bezingen",
          "goden, begunstig mijn ondernemingen (want gij veranderdet ook die)",
          "blaas mijn werk aan en leid van het allereerste begin van de wereld",
          "tot mijn eigen tijden een ononderbroken lied!",
          "Vóór de zee en het land en de hemel die alles bedekt",
          "was er in de hele wereld één gezicht van de natuur,",
          "dat men chaos noemde: een ruwe, ongeordende massa,",
          "niets dan dood gewicht, en in hetzelfde punt samengehoopt",
          "de onharmonieuze kiemen van slecht verbonden dingen.",
          "Nog verlichtte geen Titan de wereld,",
          "noch vernieuwde de wassende Phoebe haar witte hoorns,",
          "noch hing de aarde in de omringende lucht",
          "door haar eigen gewicht in evenwicht; noch had Amphitrite",
          "haar armen langs de verre kusten van de wereld uitgestrekt;",
          "en hoewel er land was en zee en lucht,",
          "was het land onvast, het water onbevaarbaar,",
          "de lucht zonder licht; niets behield zijn vorm,",
          "het ene stond het andere in de weg, want in één lichaam",
          "streed het koude met het warme, het vochtige met het droge,",
          "het zachte met het harde, het gewichtloze met het zware.",
          "Deze strijd beëindigde een god en een betere orde der natuur.",
          "Want hij scheidde de aarde van de hemel en het water van het land",
          "en de heldere hemel van de dichte lucht.",
          "Toen hij de elementen had ontward en uit de duistere hoop bevrijd,",
          "verbond hij ze, gescheiden naar hun plaats, in harmonische vrede:",
          "het vuurkrachtige, gewichtloze gewelf van de hemel",
          "schoot op en maakte zich een plaats in de hoogste hoogte;",
          "de lucht is het naast in lichtheid en plaats;",
          "de aarde, dichter dan beide, trok de grootste elementen aan",
          "en werd door haar eigen zwaarte samengeperst; het omvloeiende water",
          "nam de laatste plaats in en omsloot de vaste aardbol.",
          "Toen wie het ook was van de goden de zo geordende",
          "massa had doorsneden en in delen verdeeld,",
          "vormde hij eerst de aarde, opdat zij van alle kanten",
          "gelijk zou zijn, tot een bol van grote omvang.",
          "Toen beval hij de zeeën zich uit te breiden en te zwellen",
          "in snelle winden en de kusten van het omringde land te omspoelen;",
          "hij voegde bronnen toe en uitgestrekte meren en poelen",
          "en omgaf de aflopende rivieren met schuine oevers,",
          "die, op verschillende plaatsen, deels door de aarde zelf worden opgeslokt,",
          "deels de zee bereiken en, ontvangen op de vlakte",
          "van het vrijere water, kusten in plaats van oevers beuken.",
          "Hij beval de vlakten zich uit te strekken, de valleien te dalen,",
          "de bossen zich met loof te bedekken, de steenachtige bergen te rijzen,",
          "en zoals twee zones de hemel rechts en evenveel links",
          "doorsnijden, en een vijfde heter is dan die,",
          "zo onderscheidde de zorg van de god het omsloten gewicht in hetzelfde aantal,",
          "en evenveel streken drukken op de aarde.",
          "Waarvan de middelste onbewoonbaar is door de hitte;",
          "diepe sneeuw bedekt de twee polen; evenveel plaatste hij ertussen",
          "en gaf ze een gematigd klimaat van warmte gemengd met koude.",
          "Daarboven hangt de lucht, die zoveel zwaarder is dan vuur",
          "als het gewicht van water lichter is dan dat van de aarde.",
          "Daar beval hij de nevels en wolken zich te vestigen",
          "en donders die de menselijke geest doen beven",
          "en winden die met bliksemflitsen bliksemschichten maken.",
          "Ook de lucht stond de maker van de wereld niet onbeperkt toe",
          "aan deze toe; zelfs nu worden zij nauwelijks tegengehouden,",
          "hoewel elk zijn vlagen in een verschillende richting stuurt,",
          "van het verscheuren van de wereld; zo groot is de tweedracht der broers.",
          "Eurus week terug naar Aurora en de Nabatese rijken",
          "en Perzië en de bergtoppen onder het ochtendlicht;",
          "de avond en de kusten die gloeien in de ondergaande zon",
          "zijn het dichtst bij Zephyrus; het ijzige Scythië en de Grote Beer",
          "nam de huiveringwekkende Boreas in; het tegenoverliggende land",
          "wordt doorweekt door aanhoudende wolken en regen van de Zuidenwind.",
          "Hierboven plaatste hij de doorzichtige, gewichtloze",
          "ether, vrij van elk aards bezinksel.",
          "Nauwelijks had hij alles zo binnen vaste grenzen gescheiden,",
          "toen de sterren, lang verborgen in blinde duisternis,",
          "begonnen op te vlammen over de hele hemel;",
          "en opdat geen streek verstoken zou zijn van haar eigen levende wezens,",
          "bezetten de sterren en godengestalten de hemelvloer,",
          "de golven weken voor de glanzende vissen,",
          "de aarde ontving de wilde dieren, de bewegelijke lucht de vogels.",
          "Een heiliger schepsel, met een hogere geest begaafd,",
          "ontbrak nog, een dat over de rest kon heersen:",
          "de mens werd geboren, hetzij de goddelijke schepper hem",
          "maakte uit goddelijk zaad, oorsprong van een betere wereld,",
          "hetzij de pas geschapen aarde, kort tevoren gescheiden van de hoge",
          "ether, nog verwante hemelse kiemen bevatte.",
          "Die mengde Prometheus, de zoon van Iapetus, met regenwater",
          "en vormde ze naar het beeld van de allesbesturende goden,",
          "en terwijl de andere dieren naar de grond kijken,",
          "gaf hij de mens een opgeheven gelaat en beval hem",
          "naar de hemel te kijken en zijn blik op te heffen naar de sterren:",
          "zo nam de aarde, die kort tevoren ruw en vormloos was geweest,",
          "de onbekende gestalten van mensen aan.",
          "Het gouden tijdperk was als eerste gezaaid, dat zonder bestraffer,",
          "uit eigen beweging, zonder wet, trouw en het goede vereerde.",
          "Straf en angst ontbraken; er werden geen dreigende woorden",
          "in brons gegraveerd gelezen; geen smekende menigte vreesde",
          "het gezicht van haar rechter: zonder bestraffer waren zij veilig.",
          "Nog was geen pijnboom, op haar eigen bergen gekapt,",
          "in de vloeibare golven afgedaald om vreemde landen te bezoeken;",
          "en geen stervelingen kenden andere kusten dan de hunne;",
          "nog omringden geen steile grachten de steden;",
          "geen rechte trompet, geen gebogen koperen hoorn,",
          "geen helm, geen zwaard bestond: zonder leger",
          "brachten de volkeren hun dagen door in zachte vrede en rust.",
          "De aarde zelf ook, ongeploegd en door geen houweel aangeraakt",
          "en door geen ploegijzer gewond, gaf uit zichzelf alles,",
          "en tevreden met voedsel dat zonder dwang was gegroeid",
          "plukten zij aardbeien en bergframbozen",
          "en kornoeljen en aan de ruwe braamstruiken hangende moerbeien",
          "en de eikels die van Jupiters brede boom waren gevallen.",
          "De lente was eeuwig, en zachte westwinden streelden",
          "met warme lucht de bloemen die zonder zaad waren gegroeid;",
          "weldra droeg de ongeploegde aarde ook vruchten,",
          "en het niet-vernieuwde veld werd wit van zware korenaren;",
          "er vloeiden rivieren van melk en rivieren van nectar,",
          "en gele honing druppelde van de groene steeneik.",
          "Nadat Saturnus naar het duistere Tartarus was gezonden",
          "en de wereld onder Jupiter stond, kwam het zilveren geslacht,",
          "slechter dan het gouden, kostbaarder dan het gele brons.",
          "Jupiter bekortte de duur van de lente van weleer",
          "en liet door winters en zomers en ongelijke herfsten",
          "en een korte lente het jaar verlopen in vier periodes.",
          "Toen eerst gloeide de lucht wit, verschroeid door droge hitte,",
          "en hing ijs, vastgemaakt door de wind;",
          "toen eerst betraden zij huizen; huizen waren grotten",
          "en dichte struiken en met bast samengebonden twijgen.",
          "Toen eerst werden de zaden van Ceres in lange voren",
          "begraven, en kreunden de jonge stieren onder het juk.",
          "Als derde volgde na die het bronzen geslacht op,",
          "woester van aard en sneller geneigd tot verschrikkelijke wapens,",
          "maar toch niet misdadig; van hard ijzer is het laatste.",
          "Onmiddellijk brak in het tijdperk van dat slechtere metaal",
          "alle kwaad los: schaamte, waarheid en trouw vluchtten;",
          "in hun plaats traden bedrog en list",
          "en hinderlagen en geweld en misdadige hebzucht.",
          "Zij spreidden de zeilen voor de wind, en de zeeman kende die",
          "nog niet goed; de kielen, die eerst op hoge bergen hadden gestaan,",
          "dansten op onbekende golven;",
          "en de grond, die eerst als het zonlicht en de lucht gemeenschappelijk was,",
          "merkte de voorzichtige landmeter af met lange grenzen.",
          "Niet alleen oogsten en verschuldigd voedsel",
          "eiste men van de rijke bodem, maar men drong door in de ingewanden der aarde,",
          "en de schatten die zij had verborgen en naar de Stygische schaduwen gebracht,",
          "werden opgegraven, prikkels tot het kwaad.",
          "En reeds was het schadelijke ijzer tevoorschijn gekomen, en goud, schadelijker dan ijzer;",
          "de oorlog verscheen, die met beide strijdt,",
          "en schudt kletterend wapens met bebloede hand.",
          "Men leeft van roof: geen gast is veilig bij zijn gastheer,",
          "geen schoonvader bij zijn schoonzoon; ook tussen broeders is genegenheid zeldzaam;",
          "de man loert op de dood van zijn vrouw, zij op die van haar man;",
          "gruwelijke stiefmoeders mengen dodelijk gif;",
          "de zoon vraagt vóór de tijd naar de jaren van zijn vader:",
          "de vroomheid ligt verslagen, en de maagd Astraea, de laatste",
          "van de hemelbewoners, verliet de met bloed doordrenkte aarde."
        ]
      }

    ]
  },
  // ─── GREEK ────────────────────────────────────────────────────────────
  // BOOK 3: Homerus — Ilias I
  { id: "homer-iliad-1", title: "Homerus — Ilias I", author: "Homerus", year: -800, lang: "greek",
    chapters: [
      {
        title: "Rhapsodia I — De toorn van Achilleus (Curriculum)",
        lines: [
          "Μῆνιν ἄειδε, θεά, Πηληιάδεω Ἀχιλῆος",
          "οὐλομένην, ἣ μυρί Ἀχαιοῖς ἄλγε' ἔθηκε",
          "πολλὰς δ' ἰφθίμους ψυχὰς Ἄϊδι προΐαψεν",
          "ἡρώων, αὐτοὺς δὲ ἑλώρια τεῦχε κύνεσσιν",
          "οἰωνοῖσί τε — Διὸς δ' ἐτελείετο βουλή —"
        ],
        translation: [
          "Zing, godin, de verwoestende toorn van Achilleus, de zoon van Peleus",
          "die ontelbare ellende bracht aan de Achaeërs",
          "en vele moedige zielen naar de Hades zond",
          "van helden, en hen zelf tot prooi maakte voor de honden",
          "en de vogels — de wil van Zeus voltrok zich —"
        ]
      },
      // Chapter 1 — Full Iliad I (Curriculum) ~ lines 1-100
      {
        title: "Rhapsodia I — volledige tekst (Curriculum)",
        lines: [
          "μῆνιν ἄειδε θεὰ Πηληϊάδεω Ἀχιλῆος",
          "οὐλομένην, ἣ μυρί' Ἀχαιοῖς ἄλγε' ἔθηκε,",
          "πολλὰς δ' ἰφθίμους ψυχὰς Ἄϊδι προΐαψεν",
          "ἡρώων, αὐτοὺς δὲ ἑλώρια τεῦχε κύνεσσιν",
          "οἰωνοῖσί τε πᾶσι, Διὸς δ' ἐτελείετο βουλή,",
          "ἐξ οὗ δὴ τὰ πρῶτα διαστήτην ἐρίσαντε",
          "Ἀτρεΐδης τε ἄναξ ἀνδρῶν καὶ δῖος Ἀχιλλεύς.",
          "τίς τ' ἄρ σφωε θεῶν ἔριδι ξυνέηκε μάχεσθαι;",
          "Λητοῦς καὶ Διὸς υἱός· ὃ γὰρ βασιλῆϊ χολωθεὶς",
          "νοῦσον ἀνὰ στρατὸν ὄρσε κακήν, ὀλέκοντο δὲ λαοί,",
          "οὕνεκα τὸν Χρύσην ἠτίμασεν ἀρητῆρα",
          "Ἀτρεΐδης· ὃ γὰρ ἦλθε θοὰς ἐπὶ νῆας Ἀχαιῶν",
          "λυσόμενός τε θύγατρα φέρων τ' ἀπερείσι' ἄποινα,",
          "στέμματ' ἔχων ἐν χερσὶν ἑκηβόλου Ἀπόλλωνος",
          "χρυσέῳ ἀνὰ σκήπτρῳ, καὶ λίσσετο πάντας Ἀχαιούς,",
          "Ἀτρεΐδα δὲ μάλιστα δύω, κοσμήτορε λαῶν·",
          "Ἀτρεΐδαι τε καὶ ἄλλοι ἐϋκνήμιδες Ἀχαιοί,",
          "ὑμῖν μὲν θεοὶ δοῖεν Ὀλύμπια δώματ' ἔχοντες",
          "ἐκπέρσαι Πριάμοιο πόλιν, εὖ δ' οἴκαδ' ἱκέσθαι·",
          "παῖδα δ' ἐμοὶ λύσαιτε φίλην, τὰ δ' ἄποινα δέχεσθαι,",
          "ἁζόμενοι Διὸς υἱὸν ἑκηβόλον Ἀπόλλωνα.",
          "ἔνθ' ἄλλοι μὲν πάντες ἐπευφήμησαν Ἀχαιοὶ",
          "αἰδεῖσθαί θ' ἱερῆα καὶ ἀγλαὰ δέχθαι ἄποινα·",
          "ἀλλ' οὐκ Ἀτρεΐδῃ Ἀγαμέμνονι ἥνδανε θυμῷ,",
          "ἀλλὰ κακῶς ἀφίει, κρατερὸν δ' ἐπὶ μῦθον ἔτελλε·",
          "μή σε γέρον κοίλῃσιν ἐγὼ παρὰ νηυσὶ κιχείω",
          "ἢ νῦν δηθύνοντ' ἢ ὕστερον αὖτις ἰόντα,",
          "μή νύ τοι οὐ χραίσμῃ σκῆπτρον καὶ στέμμα θεοῖο·",
          "τὴν δ' ἐγὼ οὐ λύσω· πρίν μιν καὶ γῆρας ἔπεισιν",
          "ἡμετέρῳ ἐνὶ οἴκῳ ἐν Ἄργεϊ τηλόθι πάτρης",
          "ἱστὸν ἐποιχομένην καὶ ἐμὸν λέχος ἀντιόωσαν·",
          "ἀλλ' ἴθι μή μ' ἐρέθιζε σαώτερος ὥς κε νέηαι.",
          "ὣς ἔφατ', ἔδεισεν δ' ὃ γέρων καὶ ἐπείθετο μύθῳ·",
          "βῆ δ' ἀκέων παρὰ θῖνα πολυφλοίσβοιο θαλάσσης·",
          "πολλὰ δ' ἔπειτ' ἀπάνευθε κιὼν ἠρᾶθ' ὃ γεραιὸς",
          "Ἀπόλλωνι ἄνακτι, τὸν ἠΰκομος τέκε Λητώ·",
          "κλῦθί μευ ἀργυρότοξ', ὃς Χρύσην ἀμφιβέβηκας",
          "Κίλλάν τε ζαθέην Τενέδοιό τε ἶφι ἀνάσσεις,",
          "Σμινθεῦ εἴ ποτέ τοι χαρίεντ' ἐπὶ νηὸν ἔρεψα,",
          "ἢ εἰ δή ποτέ τοι κατὰ πίονα μηρί' ἔκηα",
          "ταύρων ἠδ' αἰγῶν, τὸ δέ μοι κρήηνον ἐέλδωρ·",
          "τίσειαν Δαναοὶ ἐμὰ δάκρυα σοῖσι βέλεσσιν.",
          "ὣς ἔφατ' εὐχόμενος, τοῦ δ' ἔκλυε Φοῖβος Ἀπόλλων,",
          "βῆ δὲ κατ' Οὐλύμποιο καρήνων χωόμενος κῆρ,",
          "τόξ' ὤμοισιν ἔχων ἀμφηρεφέα τε φαρέτρην·",
          "ἔκλαγξαν δ' ἄρ' ὀϊστοὶ ἐπ' ὤμων χωομένοιο,",
          "αὐτοῦ κινηθέντος· ὃ δ' ἤϊε νυκτὶ ἐοικώς.",
          "ἕζετ' ἔπειτ' ἀπάνευθε νεῶν, μετὰ δ' ἰὸν ἕηκε·",
          "δεινὴ δὲ κλαγγὴ γένετ' ἀργυρέοιο βιοῖο·",
          "οὐρῆας μὲν πρῶτον ἐπῴχετο καὶ κύνας ἀργούς,",
          "αὐτὰρ ἔπειτ' αὐτοῖσι βέλος ἐχεπευκὲς ἐφιεὶς",
          "βάλλ'· αἰεὶ δὲ πυραὶ νεκύων καίοντο θαμειαί.",
          "ἐννῆμαρ μὲν ἀνὰ στρατὸν ᾤχετο κῆλα θεοῖο,",
          "τῇ δεκάτῃ δ' ἀγορὴν δὲ καλέσσατο λαὸν Ἀχιλλεύς·",
          "τῷ γὰρ ἐπὶ φρεσὶ θῆκε θεὰ λευκώλενος Ἥρη·",
          "κήδετο γὰρ Δαναῶν, ὅτι ῥα θνήσκοντας ὁρᾶτο.",
          "οἳ δ' ἐπεὶ οὖν ἤγερθεν ὁμηγερέες τε γένοντο,",
          "τοῖσι δ' ἀνιστάμενος μετέφη πόδας ὠκὺς Ἀχιλλεύς·",
          "Ἀτρεΐδη νῦν ἄμμε παλιμπλαγχθέντας ὀΐω",
          "ἂψ ἀπονοστήσειν, εἴ κεν θάνατόν γε φύγοιμεν,",
          "εἰ δὴ ὁμοῦ πόλεμός τε δαμᾷ καὶ λοιμὸς Ἀχαιούς·",
          "ἀλλ' ἄγε δή τινα μάντιν ἐρείομεν ἢ ἱερῆα",
          "ἢ καὶ ὀνειροπόλον, καὶ γάρ τ' ὄναρ ἐκ Διός ἐστιν,",
          "ὅς κ' εἴποι ὅ τι τόσσον ἐχώσατο Φοῖβος Ἀπόλλων,",
          "εἴτ' ἄρ' ὅ γ' εὐχωλῆς ἐπιμέμφεται ἠδ' ἑκατόμβης,",
          "αἴ κέν πως ἀρνῶν κνίσης αἰγῶν τε τελείων",
          "βούλεται ἀντιάσας ἡμῖν ἀπὸ λοιγὸν ἀμῦναι.",
          "ἤτοι ὅ γ' ὣς εἰπὼν κατ' ἄρ' ἕζετο· τοῖσι δ' ἀνέστη",
          "Κάλχας Θεστορίδης οἰωνοπόλων ὄχ' ἄριστος,",
          "ὃς ᾔδη τά τ' ἐόντα τά τ' ἐσσόμενα πρό τ' ἐόντα,",
          "καὶ νήεσσ' ἡγήσατ' Ἀχαιῶν Ἴλιον εἴσω",
          "ἣν διὰ μαντοσύνην, τήν οἱ πόρε Φοῖβος Ἀπόλλων·",
          "ὅ σφιν ἐὺ φρονέων ἀγορήσατο καὶ μετέειπεν·",
          "ὦ Ἀχιλεῦ κέλεαί με Διὶ φίλε μυθήσασθαι",
          "μῆνιν Ἀπόλλωνος ἑκατηβελέταο ἄνακτος·",
          "τοὶ γὰρ ἐγὼν ἐρέω· σὺ δὲ σύνθεο καί μοι ὄμοσσον",
          "ἦ μέν μοι πρόφρων ἔπεσιν καὶ χερσὶν ἀρήξειν·",
          "ἦ γὰρ ὀΐομαι ἄνδρα χολωσέμεν, ὃς μέγα πάντων",
          "Ἀργείων κρατέει καί οἱ πείθονται Ἀχαιοί·",
          "κρείσσων γὰρ βασιλεὺς ὅτε χώσεται ἀνδρὶ χέρηϊ·",
          "εἴ περ γάρ τε χόλον γε καὶ αὐτῆμαρ καταπέψῃ,",
          "ἀλλά τε καὶ μετόπισθεν ἔχει κότον, ὄφρα τελέσσῃ,",
          "ἐν στήθεσσιν ἑοῖσι· σὺ δὲ φράσαι εἴ με σαώσεις.",
          "τὸν δ' ἀπαμειβόμενος προσέφη πόδας ὠκὺς Ἀχιλλεύς·",
          "θαρσήσας μάλα εἰπὲ θεοπρόπιον ὅ τι οἶσθα·",
          "οὐ μὰ γὰρ Ἀπόλλωνα Διὶ φίλον, ᾧ τε σὺ Κάλχαν",
          "εὐχόμενος Δαναοῖσι θεοπροπίας ἀναφαίνεις,",
          "οὔ τις ἐμεῦ ζῶντος καὶ ἐπὶ χθονὶ δερκομένοιο",
          "σοὶ κοίλῃς παρὰ νηυσί βαρείας χεῖρας ἐποίσει",
          "συμπάντων Δαναῶν, οὐδ' ἢν Ἀγαμέμνονα εἴπῃς,",
          "ὃς νῦν πολλὸν ἄριστος Ἀχαιῶν εὔχεται εἶναι.",
          "καὶ τότε δὴ θάρσησε καὶ ηὔδα μάντις ἀμύμων·",
          "οὔ τ' ἄρ ὅ γ' εὐχωλῆς ἐπιμέμφεται οὐδ' ἑκατόμβης,",
          "ἀλλ' ἕνεκ' ἀρητῆρος ὃν ἠτίμησ' Ἀγαμέμνων,",
          "οὐδ' ἀπέλυσε θύγατρα καὶ οὐκ ἀπεδέξατ' ἄποινα,",
          "τοὔνεκ' ἄρ' ἄλγε' ἔδωκεν ἑκηβόλος ἠδ' ἔτι δώσει·",
          "οὐδ' ὅ γε πρὶν Δαναοῖσιν ἀεικέα λοιγὸν ἀπώσει",
          "πρίν γ' ἀπὸ πατρὶ φίλῳ δόμεναι ἑλικώπιδα κούρην",
          "ἀπριάτην ἀνάποινον, ἄγειν θ' ἱερὴν ἑκατόμβην",
          "ἐς Χρύσην· τότε κέν μιν ἱλασσάμενοι πεπίθοιμεν."
        ],
        translation: [
          "Sing, goddess, the anger of Achilles, Peleus' son,",
          "that fatal anger that brought countless sorrows on the Greeks,",
          "and sent many valiant souls of warriors down to Hades,",
          "leaving their bodies as spoil for dogs",
          "and carrion birds: for thus was the will of Zeus brought to fulfilment.",
          "Sing of it from the moment when Agamemnon, Atreus' son,",
          "that king of men, parted in wrath from noble Achilles.",
          "Which of the gods set these two to quarrel?",
          "Apollo, the son of Leto and Zeus, angered by the king,",
          "brought an evil plague on the army, so that the men were dying,",
          "for the son of Atreus had dishonoured Chryses the priest.",
          "He it was who came to the swift Achaean ships,",
          "to free his daughter, bringing a wealth of ransom,",
          "carrying a golden staff adorned with the ribbons of far-striking Apollo,",
          "and called out to the Achaeans, above all",
          "to the two leaders of armies, those sons of Atreus:",
          "'Sons of Atreus, and all you bronze-greaved Achaeans,",
          "may the gods who live on Olympus grant you",
          "to sack Priam's city, and sail back home in safety;",
          "but take this ransom, and free my darling child;",
          "show reverence for Zeus's son, far-striking Apollo.'",
          "Then the rest of the Achaeans shouted in agreement,",
          "that the priest should be respected, and the fine ransom taken;",
          "but this troubled the heart of Agamemnon, son of Atreus,",
          "and he dismissed the priest harshly, and dealt with him sternly:",
          "'Old man, don't let me catch you loitering by the hollow ships today,",
          "and don't be back later, or come again,",
          "lest your staff and the god's ribbons fail to protect you.",
          "Her, I shall not free; old age will claim her first,",
          "far from her own country, in Argos, my home,",
          "where she can tend the loom, and share my bed.",
          "Away now; don't provoke me if you'd leave safely.'",
          "So he spoke, and the old man, seized by fear, obeyed.",
          "Silently, he walked the shore of the echoing sea;",
          "and when he was quite alone, the old man prayed deeply",
          "to Lord Apollo, the son of bright-haired Leto:",
          "'Hear me, Silver Bow, protector of Chryse",
          "and holy Cilla, high lord of Tenedos:",
          "if ever I built a shrine that pleased you,",
          "if ever I burned the fat thighs of a bull or goat for you,",
          "grant my wish: with your arrows",
          "make the Greeks pay for my tears.'",
          "So he prayed, and Phoebus Apollo heard him.",
          "Down he came, in fury, from the heights of Olympus,",
          "with his bow and inlaid quiver at his back.",
          "The arrows rattled at his shoulder as the god descended,",
          "in anger. He set down by the ships like the night.",
          "He sat apart from the ships, and fired a shaft;",
          "and a fearful twang came from the silver bow.",
          "First he attacked the mules, and the swift hounds,",
          "then loosed his vicious darts at the men;",
          "so the dense pyres for the dead burned endlessly.",
          "For nine days the god's arrows fell on the army,",
          "and on the tenth Achilles called them to the Assembly;",
          "his heart stirred by the goddess, white-armed Hera,",
          "she pitying the Greeks, whose deaths she witnessed.",
          "And when they had assembled, and the gathering was complete,",
          "swift-footed Achilles rose and spoke:",
          "'Son of Atreus, if war and plague alike are fated to defeat us,",
          "I think we shall be driven to head for home,",
          "if indeed we can escape death.",
          "But why not consult some priest, some prophet,",
          "or interpreter of dreams — for dreams too come from Zeus —",
          "one who can tell why Phoebus Apollo shows such anger,",
          "because of some broken vow perhaps, or some missed sacrifice;",
          "in hopes the god might accept succulent lambs or goats,",
          "and choose to avert our ruin.'",
          "He sat down when he had spoken, and Calchas rose,",
          "Calchas, son of Thestor, peerless among augurs,",
          "who knew all things past, all things to come, and all things present,",
          "who had guided the Greek fleet to Ilium",
          "through the gift of prophecy granted him by Apollo.",
          "He, with virtuous intent, spoke to the gathering:",
          "'Achilles, god-beloved, you ask that I explain",
          "far-striking Apollo's anger.",
          "Well, I will, but take thought, and swear to me",
          "you'll be ready to defend me with strength and word;",
          "for I believe I'll anger the man who rules",
          "the Argives in his might, whom all the Achaeans obey.",
          "For a king in his anger crushes a lesser man.",
          "Even if he swallows anger for a while,",
          "he will nurse resentment till he chooses to repay,",
          "in his breast. Consider then, if you can keep me safe.'",
          "Swift-footed Achilles spoke in reply:",
          "'Courage, and say out what truth you know;",
          "for by Apollo, to whom you pray, Calchas,",
          "whose utterances you grant to the Greeks,",
          "none shall lay hand on you beside the hollow ships,",
          "no Greek while I live and see the earth,",
          "not even if it's Agamemnon you mean,",
          "who counts himself the best of the Achaeans.'",
          "Then the peerless seer took heart, and spoke:",
          "'Not for a broken vow, or a missed sacrifice,",
          "but because of that priest whom Agamemnon offended,",
          "refusing the ransom, refusing to free his daughter.",
          "That is why the far-striker makes us suffer, and will do so,",
          "and will not rid the Greeks of loathsome plague,",
          "until we return the bright-eyed girl to her father",
          "without recompense or ransom, and send a sacred offering",
          "to Chryse; then we might persuade him to relent.'"
        ]
      }

    ]
  },
  // BOOK 4: Sophocles — Oedipus Rex
  { id: "sophocles-oedipus", title: "Sophocles — Oedipus Rex", author: "Sophocles", year: -429, lang: "greek",
    chapters: [
      {
        title: "Oedipus Tyrannus (Curriculum)",
        lines: [
          "ὦ τέκνα, Κάδμου τοῦ πάλαι νέα τροφή",
          "τίνας ποθ' ἕδρας τάσδε μοι θοάζετε",
          "ἱκτηρίοις κλάδοισιν ἐστεμμένοι",
          "πόλις δ' ὁμοῦ μὲν θυμιαμάτων γέμει",
          "ὁμοῦ δὲ παιάνων τε καὶ στεναγμάτων"
        ],
        translation: [
          "O kinderen, nieuwe nakomelingen van de oude Kadmos",
          "waarom zit gij op deze plaatsen voor mij",
          "met smeekbede-takken omkranst",
          "De stad is vol van wierookgeuren",
          "en van overwinningszangen en van weeklachten"
        ]
      },
      // Chapter 1 — Full Oedipus Rex (Curriculum) ~ lines 1-77
      {
        title: "Oedipus Tyrannus — volledige tekst (Curriculum)",
        lines: [
          "ὦ τέκνα, Κάδμου τοῦ πάλαι νέα τροφή,",
          "τίνας ποθ᾽ ἕδρας τάσδε μοι θοάζετε",
          "ἱκτηρίοις κλάδοισιν ἐξεστεμμένοι;",
          "πόλις δ᾽ ὁμοῦ μὲν θυμιαμάτων γέμει,",
          "ὁμοῦ δὲ παιάνων τε καὶ στεναγμάτων·",
          "ἁγὼ δικαιῶν μὴ παρ᾽ ἀγγέλων, τέκνα,",
          "ἄλλων ἀκούειν αὐτὸς ὧδ᾽ ἐλήλυθα,",
          "ὁ πᾶσι κλεινὸς Οἰδίπους καλούμενος.",
          "ἀλλ᾽ ὦ γεραιέ, φράζ᾽, ἐπεὶ πρέπων ἔφυς",
          "πρὸ τῶνδε φωνεῖν, τίνι τρόπῳ καθέστατε,",
          "δείσαντες ἢ στέρξαντες; ὡς θέλοντος ἂν",
          "ἐμοῦ προσαρκεῖν πᾶν· δυσάλγητος γὰρ ἂν",
          "εἴην τοιάνδε μὴ οὐ κατοικτίρων ἕδραν.",
          "ἀλλ᾽ ὦ κρατύνων Οἰδίπους χώρας ἐμῆς,",
          "ὁρᾷς μὲν ἡμᾶς ἡλίκοι προσήμεθα",
          "βωμοῖσι τοῖς σοῖς· οἱ μὲν οὐδέπω μακρὰν",
          "πτέσθαι σθένοντες, οἱ δὲ σὺν γήρᾳ βαρεῖς,",
          "ἱερῆς, ἐγὼ μὲν Ζηνός, οἵδε τ᾽ ᾐθέων",
          "λεκτοί· τὸ δ᾽ ἄλλο φῦλον ἐξεστεμμένον",
          "ἀγοραῖσι θακεῖ πρός τε Παλλάδος διπλοῖς",
          "ναοῖς, ἐπ᾽ Ἰσμηνοῦ τε μαντείᾳ σποδῷ.",
          "πόλις γάρ, ὥσπερ καὐτὸς εἰσορᾷς, ἄγαν",
          "ἤδη σαλεύει κἀνακουφίσαι κάρα",
          "βυθῶν ἔτ᾽ οὐχ οἵα τε φοινίου σάλου,",
          "φθίνουσα μὲν κάλυξιν ἐγκάρποις χθονός,",
          "φθίνουσα δ᾽ ἀγέλαις βουνόμοις τόκοισί τε",
          "ἀγόνοις γυναικῶν· ἐν δ᾽ ὁ πυρφόρος θεὸς",
          "σκήψας ἐλαύνει, λοιμὸς ἔχθιστος, πόλιν,",
          "ὑφ᾽ οὗ κενοῦται δῶμα Καδμεῖον, μέλας δ᾽",
          "Ἅιδης στεναγμοῖς καὶ γόοις πλουτίζεται.",
          "θεοῖσι μέν νυν οὐκ ἰσούμενόν σ᾽ ἐγὼ",
          "οὐδ᾽ οἵδε παῖδες ἑζόμεσθ᾽ ἐφέστιοι,",
          "ἀνδρῶν δὲ πρῶτον ἔν τε συμφοραῖς βίου",
          "κρίνοντες ἔν τε δαιμόνων συναλλαγαῖς·",
          "ὅς γ᾽ ἐξέλυσας ἄστυ Καδμεῖον μολὼν",
          "σκληρᾶς ἀοιδοῦ δασμὸν ὃν παρείχομεν,",
          "καὶ ταῦθ᾽ ὑφ᾽ ἡμῶν οὐδὲν ἐξειδὼς πλέον",
          "οὐδ᾽ ἐκδιδαχθείς, ἀλλὰ προσθήκῃ θεοῦ",
          "λέγει νομίζει θ᾽ ἡμὶν ὀρθῶσαι βίον·",
          "νῦν τ᾽, ὦ κράτιστον πᾶσιν Οἰδίπου κάρα,",
          "ἱκετεύομέν σε πάντες οἵδε πρόστροποι",
          "ἀλκήν τιν᾽ εὑρεῖν ἡμίν, εἴτε του θεῶν",
          "φήμην ἀκούσας εἴτ᾽ ἀπ᾽ ἀνδρὸς οἶσθά του·",
          "ὡς τοῖσιν ἐμπείροισι καὶ τὰς ξυμφορὰς",
          "ζώσας ὁρῶ μάλιστα τῶν βουλευμάτων.",
          "ἴθ᾽, ὦ βροτῶν ἄριστ᾽, ἀνόρθωσον πόλιν,",
          "ἴθ᾽, εὐλαβήθηθ᾽· ὡς σὲ νῦν μὲν ἥδε γῆ",
          "σωτῆρα κλῄζει τῆς πάρος προθυμίας·",
          "ἀρχῆς δὲ τῆς σῆς μηδαμῶς μεμνώμεθα",
          "στάντες τ᾽ ἐς ὀρθὸν καὶ πεσόντες ὕστερον.",
          "ἀλλ᾽ ἀσφαλείᾳ τήνδ᾽ ἀνόρθωσον πόλιν·",
          "ὄρνιθι γὰρ καὶ τὴν τότ᾽ αἰσίῳ τύχην",
          "παρέσχες ἡμῖν, καὶ τανῦν ἴσος γενοῦ.",
          "ὡς εἴπερ ἄρξεις τῆσδε γῆς, ὥσπερ κρατεῖς,",
          "ξὺν ἀνδράσιν κάλλιον ἢ κενῆς κρατεῖν·",
          "ὡς οὐδέν ἐστιν οὔτε πύργος οὔτε ναῦς",
          "ἔρημος ἀνδρῶν μὴ ξυνοικούντων ἔσω.",
          "ὦ παῖδες οἰκτροί, γνωτὰ κοὐκ ἄγνωτά μοι",
          "προσήλθεθ᾽ ἱμείροντες· εὖ γὰρ οἶδ᾽ ὅτι",
          "νοσεῖτε πάντες, καὶ νοσοῦντες, ὡς ἐγὼ",
          "οὐκ ἔστιν ὑμῶν ὅστις ἐξ ἴσου νοσεῖ.",
          "τὸ μὲν γὰρ ὑμῶν ἄλγος εἰς ἕν᾽ ἔρχεται",
          "μόνον καθ᾽ αὑτὸν κοὐδέν᾽ ἄλλον, ἡ δ᾽ ἐμὴ",
          "ψυχὴ πόλιν τε κἀμὲ καὶ σ᾽ ὁμοῦ στένει.",
          "ὥστ᾽ οὐχ ὕπνῳ γ᾽ εὕδοντά μ᾽ ἐξεγείρετε,",
          "ἀλλ᾽ ἴστε πολλὰ μέν με δακρύσαντα δή,",
          "πολλὰς δ᾽ ὁδοὺς ἐλθόντα φροντίδος πλάνοις·",
          "ἣν δ᾽ εὖ σκοπῶν ηὕρισκον ἴασιν μόνην,",
          "ταύτην ἔπραξα· παῖδα γὰρ Μενοικέως",
          "Κρέοντ᾽, ἐμαυτοῦ γαμβρόν, ἐς τὰ Πυθικὰ",
          "ἔπεμψα Φοίβου δώμαθ᾽, ὡς πύθοιθ᾽ ὅ τι",
          "δρῶν ἢ τί φωνῶν τήνδε ῥυσαίμην πόλιν.",
          "καί μ᾽ ἦμαρ ἤδη ξυμμετρούμενον χρόνῳ",
          "λυπεῖ τί πράσσει· τοῦ γὰρ εἰκότος πέρα",
          "ἄπεστι πλείω τοῦ καθήκοντος χρόνου.",
          "ὅταν δ᾽ ἵκηται, τηνικαῦτ᾽ ἐγὼ κακὸς",
          "μὴ δρῶν ἂν εἴην πάνθ᾽ ὅσ᾽ ἂν δηλοῖ θεός."
        ],
        translation: [
          "O children, latest born of Cadmus' line,",
          "why do you sit here at my altars,",
          "wreathed with the branches of suppliants?",
          "The city reeks with incense,",
          "with hymns of prayer and wailing.",
          "I thought it not right, children, to hear this",
          "from others' mouths, and have come here myself,",
          "I, Oedipus, whose name is known to all.",
          "But you, old man, speak — since you are fit",
          "to speak for these — in what mood do you sit here,",
          "in fear or hope? Know that I would gladly",
          "give all aid; hard of heart would I be",
          "if I did not pity such suppliants.",
          "O Oedipus, ruler of my land,",
          "you see how old and young we sit",
          "at your altars; some not yet able to fly far,",
          "some heavy with age,",
          "priests — I of Zeus — and these, chosen youths;",
          "the rest of the people, wreathed,",
          "sit in the market places, at the twin shrines of Pallas,",
          "and at the prophetic ashes of Ismenus.",
          "For the city, as you yourself can see, is now",
          "storm-tossed, and cannot lift its head",
          "from the depths of this bloody surge:",
          "a blight upon the budding fruits of the earth,",
          "a blight upon the herds and on",
          "the barren pangs of women; and the fire-bearing god,",
          "the plague, most hateful, has swept upon the city,",
          "by whom the house of Cadmus is emptied, and dark",
          "Hades is enriched with groans and wailing.",
          "It is not as equalling the gods that I",
          "and these children sit at your hearth,",
          "but as judging you first of men in life's",
          "chances and in dealings with the divine;",
          "for you freed the city of Cadmus from the toll",
          "we paid to the harsh songstress,",
          "and that with no special knowledge from us,",
          "nor any teaching — but by a god's aid",
          "you are said to have set our life straight.",
          "And now, O Oedipus, mightiest in all men's eyes,",
          "we all turn to you as suppliants,",
          "to find some defence for us, whether by word of god",
          "or from some man you may have heard;",
          "for I see that experienced men's counsels",
          "bear living fruit above all others.",
          "Come, noblest of mortals, lift up our city!",
          "Come, guard your fame — since now this land",
          "calls you saviour for your former zeal;",
          "may we never remember of your reign",
          "that we stood upright and then fell.",
          "But raise this city to safety!",
          "With good omens you gave us that past fortune;",
          "now be equal to what you were then.",
          "For if you are to rule this land, as now you do,",
          "better to rule over men than over a waste;",
          "since neither tower nor ship is anything",
          "when emptied of men who live within.",
          "O piteous children, known to me, not unknown,",
          "are the desires with which you come; for I know well",
          "that you are all sick, and sick as you are,",
          "there is not one of you sick as I am.",
          "Your pain comes to each one alone,",
          "for himself and no other; but my soul",
          "groans for the city, for myself, and for you.",
          "So you do not wake one who sleeps:",
          "know that I have wept many tears,",
          "and wandered many ways in thought.",
          "The one remedy I found by careful search,",
          "that I have used: Creon, son of Menoeceus,",
          "my own wife's brother, I have sent to Phoebus'",
          "Pythian halls, to learn what deed",
          "or word of mine might save this city.",
          "And now, counting the days, I am troubled",
          "at what he is doing; for he is away longer",
          "than the time requires.",
          "But when he comes, then I would be a villain",
          "not to do all the god reveals."
        ]
      }

    ]
  }
];