#!/usr/bin/env python3
"""Maintain the Greek form store and regenerate imported-greek-dictionary.js.

The repo keeps two accumulated data files so imports are repeatable across
sessions without any external state:

  generated/greek-forms-store.json   form key -> [{lemma, grammar, count}]
  generated/greek-glosses.json       lemma -> {"en": ..., "nl": ...}

Adding a text is three steps:

  1. python3 scripts/build_greek_treebank_dictionary.py TEXT.txt TB.xml PREFIX
       -> PREFIX_forms.json, PREFIX_lemmas.json
  2. python3 scripts/assemble_greek_import.py merge PREFIX_forms.json
       -> merges analyses into the store, writes PREFIX_missing_glosses.json
          (the worklist of lemmas that still need {"en", "nl"} glosses).
       Fix any 'merged:' grammar strings or empty lemmas in the forms file
       BEFORE merging (see build_greek_treebank_dictionary.py output).
  3. Supply glosses for the worklist (LLM drafts these well), then:
     python3 scripts/assemble_greek_import.py add-glosses GLOSSES.json
     python3 scripts/assemble_greek_import.py build
       -> regenerates generated/imported-greek-dictionary.js; refuses to
          build while any stored lemma lacks a gloss.

Homograph forms keep every attested (lemma, grammar) analysis; entries are
rendered with all lemmas and grammars joined, most frequent first.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STORE = ROOT / "generated" / "greek-forms-store.json"
GLOSSES = ROOT / "generated" / "greek-glosses.json"
OUTPUT = ROOT / "generated" / "imported-greek-dictionary.js"

HEADER = [
    "// AUTO-GENERATED by scripts/assemble_greek_import.py. Do not edit manually.",
    "// Built from generated/greek-forms-store.json (treebank analyses) and",
    "// generated/greek-glosses.json (per-lemma glosses). Homograph forms carry",
    "// all attested analyses. See imports/README.md for the pipeline.",
    "",
    "Object.assign(GREEK_DICT, {",
]


def load_json(path, default):
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else default


def save_json(path, data):
    path.write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")


def clean_lemma(lemma):
    return lemma.replace("%", "").replace("_", "")


def cmd_merge(forms_path):
    forms_path = Path(forms_path)
    new_forms = json.loads(forms_path.read_text(encoding="utf-8"))
    store = load_json(STORE, {})
    problems = []
    for key, analyses in new_forms.items():
        bucket = {(a["lemma"], a["grammar"]): a["count"]
                  for a in store.get(key, [])}
        for a in analyses:
            lemma, grammar = clean_lemma(a["lemma"]), a["grammar"] or "-"
            if not lemma or grammar == "-" or grammar.startswith("merged:"):
                problems.append(f"{key!r}: lemma={a['lemma']!r} grammar={a['grammar']!r}")
                continue
            k = (lemma, grammar)
            bucket[k] = bucket.get(k, 0) + a["count"]
        store[key] = [{"lemma": l, "grammar": g, "count": c}
                      for (l, g), c in sorted(bucket.items(), key=lambda kv: -kv[1])]
    if problems:
        print("REFUSING TO MERGE — fix these analyses in the forms file first")
        print("(empty lemma, missing grammar, or unresolved 'merged:' entry):")
        for p in problems:
            print("  ", p)
        raise SystemExit(1)
    save_json(STORE, store)
    glosses = load_json(GLOSSES, {})
    missing = sorted({a["lemma"] for analyses in new_forms.values() for a in analyses
                      if clean_lemma(a["lemma"]) not in glosses})
    worklist = forms_path.with_name(forms_path.stem.replace("_forms", "") + "_missing_glosses.json")
    save_json(worklist, {l: {"en": "", "nl": ""} for l in missing})
    print(f"store: {len(store)} form keys after merge")
    print(f"missing glosses: {len(missing)} lemmas -> {worklist}")
    if missing:
        print("Fill in en/nl for every lemma, then run: add-glosses <file>; build")
    else:
        print("No new lemmas — run: build")


def cmd_add_glosses(glosses_path):
    incoming = json.loads(Path(glosses_path).read_text(encoding="utf-8"))
    bad = [l for l, g in incoming.items()
           if not isinstance(g, dict) or not g.get("en") or not g.get("nl")]
    if bad:
        print("REFUSING — these lemmas lack a non-empty en and nl gloss:")
        for l in bad[:20]:
            print("  ", l)
        raise SystemExit(1)
    glosses = load_json(GLOSSES, {})
    added = 0
    for lemma, g in incoming.items():
        key = clean_lemma(lemma)
        if key not in glosses:
            added += 1
        glosses[key] = {"en": g["en"], "nl": g["nl"]}
    save_json(GLOSSES, glosses)
    print(f"glosses: +{added} new, {len(glosses)} total")


def cmd_build():
    store = load_json(STORE, {})
    glosses = load_json(GLOSSES, {})
    if not store:
        raise SystemExit("empty store — run merge first")
    missing = sorted({a["lemma"] for analyses in store.values() for a in analyses
                      if a["lemma"] not in glosses})
    if missing:
        print(f"REFUSING TO BUILD — {len(missing)} lemmas lack glosses:")
        for l in missing[:30]:
            print("  ", l)
        raise SystemExit(1)
    lines = list(HEADER)
    for key in sorted(store):
        analyses = sorted(store[key], key=lambda a: -a["count"])
        lemmas_seen = []
        for a in analyses:
            if a["lemma"] not in lemmas_seen:
                lemmas_seen.append(a["lemma"])
        grammar = " | ".join(a["grammar"] for a in analyses)
        if len(lemmas_seen) == 1:
            g = glosses[lemmas_seen[0]]
            en, nl = g["en"], g["nl"]
        else:
            en = " | ".join(f"{l}: {glosses[l]['en']}" for l in lemmas_seen)
            nl = " | ".join(f"{l}: {glosses[l]['nl']}" for l in lemmas_seen)
        entry = {"lemma": " / ".join(lemmas_seen), "en": en, "nl": nl, "grammar": grammar}
        lines.append(f"  {json.dumps(key, ensure_ascii=False)}: {json.dumps(entry, ensure_ascii=False)},")
    lines.append("});")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"imported-greek-dictionary.js: {len(store)} entries")


def main():
    if len(sys.argv) >= 3 and sys.argv[1] == "merge":
        cmd_merge(sys.argv[2])
    elif len(sys.argv) >= 3 and sys.argv[1] == "add-glosses":
        cmd_add_glosses(sys.argv[2])
    elif len(sys.argv) >= 2 and sys.argv[1] == "build":
        cmd_build()
    else:
        raise SystemExit(__doc__)


if __name__ == "__main__":
    main()
