#!/usr/bin/env python3
"""Build DANISH_DICT via DeepSeek-V4.1-Flash for the word-forms in the Danish
imports (Kierkegaard, Frygt og Bæven, 1843 spelling). Bounded to the forms
actually present, like build_dutch_dictionaries.py, whose model call and key
normalisation it reuses.

Existing entries are kept and forms no longer in the text are dropped, so
adding a new unit only glosses the new forms.

Usage: python3 scripts/build_danish_dictionary.py
"""
import json
import re
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from build_dutch_dictionaries import call_model, normalise_key

ROOT = Path(__file__).resolve().parents[1]
TEXTS = sorted((ROOT / "imports").glob("kierkegaard-*/danish-*.txt"))
OUT = ROOT / "generated" / "imported-danish-dictionary.js"
BATCH_SIZE = 45
WORKERS = 6

PROMPT_TEMPLATE = """You are building click-to-gloss dictionary entries for a facing-translation
reading app. The reader is an English speaker learning Danish who also reads Dutch.
Source text: Søren Kierkegaard, Frygt og Bæven (1843), in the original spelling —
capitalised nouns, aa for å, hv-/qv- spellings, "hiin", "troer", "Kjærlighed", "gjøre".

For each word-form below (exactly as it appears in the text, lowercased — do not
normalise spelling), give a dictionary entry for the sense most likely in THIS text.
Hyphenated compounds are glossed as the whole compound.

Word-forms:
{words}

Produce STRICT JSON only — no markdown fences, no commentary — matching exactly:

{{
  "entries": [
    <one entry per word-form above, same order:
    {{
      "form": "<the exact word-form as given>",
      "def": "<concise English gloss, sense in this text first, ≤ 70 chars; for inflected forms say what the form is, e.g. 'believed (past of tro)'>",
      "nl": "<natural Dutch equivalent of the word in this sense (a Dutch gloss, not a Danish spelling). Never empty.>",
      "lemma": "<modern Danish dictionary form (e.g. 'troer' -> 'tro', 'Kjærligheden' -> 'kærlighed', 'hiin' -> 'hin')>",
      "grammar": "<brief part of speech and form, e.g. 'n. c., def. sg.', 'v., pres.', 'v., past pl. (archaic -e)', 'adj., pl.', 'pron.'; add '· mod. <spelling>' when the 1843 spelling differs from modern Danish>"
    }}>
  ]
}}

Proper names: identify them (e.g. 'Abraham — the patriarch'). German or Latin words
in the text: gloss them and mark 'German'/'Latin' in grammar. If unsure, give your best
defensible reading rather than omitting the form. Output the JSON object and nothing else."""


def word_forms() -> list[str]:
    text = "\n".join(path.read_text(encoding="utf-8") for path in TEXTS)
    forms = {w.lower() for w in re.findall(r"[^\W\d_]+", text)}
    # The reader looks a hyphenated token up whole, the coverage check by its parts.
    forms |= {w.lower() for w in re.findall(r"[^\W\d_]+(?:-[^\W\d_]+)+", text)}
    return sorted(forms)


def load_existing() -> dict:
    if not OUT.exists():
        return {}
    entries = {}
    for line in OUT.read_text(encoding="utf-8").splitlines():
        match = re.match(r'  "(.+?)": (\{.*\}),$', line)
        if match:
            entries[match.group(1)] = json.loads(match.group(2))
    return entries


def gloss_batch(batch: list[str]) -> dict:
    got: dict = {}
    missing = batch
    for _attempt in range(3):
        data = call_model(PROMPT_TEMPLATE.format(words="\n".join(missing)))
        for e in data.get("entries", []):
            key = normalise_key(e.get("form", ""))
            if key:
                got[key] = {k: e.get(k, "") for k in ("def", "nl", "grammar", "lemma")}
        missing = [w for w in batch if normalise_key(w) not in got]
        if not missing:
            return {k: got[k] for k in {normalise_key(w) for w in batch}}
    raise RuntimeError(f"forms still missing after retries: {missing}")


def main() -> int:
    forms = word_forms()
    wanted = {normalise_key(w) for w in forms}
    entries = {k: v for k, v in load_existing().items() if k in wanted}
    todo = [w for w in forms if normalise_key(w) not in entries]
    print(f"DANISH_DICT: {len(entries)} existing, {len(todo)} forms to gloss")
    batches = [todo[i : i + BATCH_SIZE] for i in range(0, len(todo), BATCH_SIZE)]
    with ThreadPoolExecutor(WORKERS) as pool:
        for n, result in enumerate(pool.map(gloss_batch, batches), start=1):
            entries.update(result)
            print(f"  batch {n}/{len(batches)} -> {len(entries)} entries")

    lines = [
        "// AUTO-GENERATED by scripts/build_danish_dictionary.py via DeepSeek-V4.1-Flash. Do not edit manually.",
        "// Scope: 1843 Danish, original spelling (Kierkegaard, Frygt og Bæven) — only the word-forms in these imports.",
        "const DANISH_DICT = {",
    ]
    lines += [f'  "{key}": {json.dumps(entries[key], ensure_ascii=False)},' for key in sorted(entries)]
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
