#!/usr/bin/env node
// Build generated/core-vocabulary.js: the Dickinson College Commentaries core
// vocabularies (Latin 1,000 words, Greek 500; CC BY-SA 3.0) with Dutch school
// glosses, plus a map from every clickable dictionary form to the rank of its
// core headword. The reader uses it to badge core words in the popup and to
// show progress towards the first-degree target of about 800 Latin words.
//
// Forms are linked through their dictionary lemma. Entries of the original
// built-in dictionary carry no lemma; Whitaker's Words supplies it for those.
//
// Usage: node scripts/build_core_vocabulary.mjs

import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";
import { createEngine, dictionaryForm } from "whitakers-words/node";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT = path.join(ROOT, "generated", "core-vocabulary.js");

function readTsv(name) {
  const [header, ...lines] = fs.readFileSync(path.join(ROOT, "data", "core-vocabulary", name), "utf8").trim().split("\n");
  const columns = header.split("\t");
  return lines.map((line) => Object.fromEntries(line.split("\t").map((cell, i) => [columns[i], cell])));
}

function stripMarks(value) {
  return String(value).normalize("NFD").replace(/\p{M}/gu, "").toLowerCase();
}

const latinKey = (value) => stripMarks(value).replace(/j/g, "i").replace(/v/g, "u").replace(/[^a-z]/g, "");
const greekKey = (value) => stripMarks(value).replace(/ς/g, "σ").replace(/[^\p{L}]/gu, "");

// The first word of a headword is the lemma ("sum esse fuī", "bonus -a -um");
// a preposition lists its variant spellings ("ā ab abs"), all of them lemmas.
function headwordKeys(row, keyOf) {
  const words = row.headword.split(/[\s,]+|\.\.\.|…/).filter((word) => word && !word.startsWith("-") && !word.startsWith("–"));
  const lemmas = /preposition/i.test(row.pos) ? words : words.slice(0, 1);
  return lemmas.map(keyOf).filter(Boolean);
}

function rankIndex(rows, keyOf) {
  const index = new Map();
  for (const row of rows) {
    for (const key of headwordKeys(row, keyOf)) {
      const rank = Number(row.rank);
      if (!index.has(key) || index.get(key) > rank) index.set(key, rank);
    }
  }
  return index;
}

function loadDictionaries() {
  const context = {};
  vm.createContext(context);
  for (const file of ["dictionary.js", "generated/imported-latin-dictionary.js", "generated/imported-greek-dictionary.js"]) {
    vm.runInContext(fs.readFileSync(path.join(ROOT, file), "utf8").replace(/^const /gm, "var "), context);
  }
  return { latin: context.LATIN_DICT, greek: context.GREEK_DICT };
}

// Every lemma a Latin form could belong to: the dictionary's own, then each
// Whitaker's analysis (arma is both a noun and a form of armo).
function latinLemmas(engine, form, entry) {
  const analysis = engine.parseWord(form);
  const results = [
    ...analysis.results, ...analysis.uniqueResults,
    ...analysis.addonResults.flatMap((addon) => addon.baseResults)
  ];
  return [entry.lemma, ...results.map((result) => dictionaryForm(result.de))];
}

// A form takes the rank of the first candidate lemma that is a core word, in
// order of trust: the dictionary's own lemma, then the form itself when it is
// a headword (sine, ita; also ventus, which Whitaker also reads as a participle
// of venio), then Whitaker's analyses in the order it ranks them.
function formRanks(dictionary, index, lemmasOf, keyOf) {
  const ranks = {};
  for (const [form, entry] of Object.entries(dictionary)) {
    const [own, ...analyses] = lemmasOf(form, entry);
    for (const lemma of [own, form, ...analyses]) {
      const rank = index.get(keyOf(String(lemma || "").split(/[\s,]+/)[0]));
      if (rank) {
        ranks[form] = rank;
        break;
      }
    }
  }
  return ranks;
}

const rows = { latin: readTsv("dcc-latin-core.tsv"), greek: readTsv("dcc-greek-core.tsv") };
const dictionaries = loadDictionaries();
const engine = createEngine();
const forms = {
  latin: formRanks(dictionaries.latin, rankIndex(rows.latin, latinKey), (form, entry) => latinLemmas(engine, form, entry), latinKey),
  greek: formRanks(dictionaries.greek, rankIndex(rows.greek, greekKey), (_form, entry) => [entry.lemma], greekKey)
};

const words = (list) => list.map((row) => [Number(row.rank), row.headword, row.en, row.nl]);
const body = {
  latin: { size: rows.latin.length, target: 800, words: words(rows.latin), forms: forms.latin },
  greek: { size: rows.greek.length, target: 250, words: words(rows.greek), forms: forms.greek }
};
fs.writeFileSync(
  OUTPUT,
  "// AUTO-GENERATED by scripts/build_core_vocabulary.mjs. Do not edit manually.\n" +
  "// Core vocabularies © Dickinson College Commentaries, CC BY-SA 3.0\n" +
  "// (https://dcc.dickinson.edu/vocab/core-vocabulary); Dutch glosses added, same licence.\n" +
  `const CORE_VOCAB = ${JSON.stringify(body)};\n`
);

for (const lang of ["latin", "greek"]) {
  const linked = new Set(Object.values(forms[lang]));
  const unlinked = rows[lang].filter((row) => !linked.has(Number(row.rank)));
  console.log(`${lang}: ${Object.keys(forms[lang]).length} forms linked to ${linked.size}/${rows[lang].length} core words`
    + (unlinked.length ? `; not met in any text yet: ${unlinked.slice(0, 12).map((row) => row.headword.split(" ")[0]).join(", ")}${unlinked.length > 12 ? " …" : ""}` : ""));
}
