#!/usr/bin/env python3
"""Build MIDDLE_DUTCH_DICT and DUTCH_DICT lookup dictionaries via DeepSeek-V4.1-Flash,
covering just the word-forms actually present in the reynaerde and
multatuli-max-havelaar imports. Bounded/scoped, not a general-purpose Dutch
dictionary — matches the "simple gloss mode" pattern (cf. build_old_english_dictionary.py
for the fuller-pipeline precedent).

Usage: python3 scripts/build_dutch_dictionaries.py
"""
import json
import re
import subprocess
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONSULT = "/Users/alexandermacmillan/private_tools/deepseek_direct_consult.py"
MODEL = "deepseek-flash"
BATCH_SIZE = 45

JOBS = [
    {
        "text_path": ROOT / "imports" / "reynaerde" / "middle_dutch.txt",
        "out_path": ROOT / "generated" / "imported-middle-dutch-dictionary.js",
        "var_name": "MIDDLE_DUTCH_DICT",
        "label": "13th-century Middle Dutch (Van den vos Reynaerde, Comburg manuscript)",
    },
    {
        "text_path": ROOT / "imports" / "multatuli-max-havelaar" / "dutch.txt",
        "out_path": ROOT / "generated" / "imported-dutch-dictionary.js",
        "var_name": "DUTCH_DICT",
        "label": "1860 Dutch, original unmodernised spelling (Multatuli, Max Havelaar)",
    },
]

PROMPT_TEMPLATE = """You are building click-to-gloss dictionary entries for a facing-translation
reading app used by a fluent Modern Dutch reader. Language of the source text: {label}.

For each of these word-forms (exactly as they appear in the source text — do not
normalise spelling), give a dictionary entry. Some forms may repeat across the list
with different apparent meaning in context; just give the single best general gloss.

Word-forms:
{words}

Produce STRICT JSON only — no markdown fences, no commentary — matching exactly:

{{
  "entries": [
    <one entry per word-form above, same order:
    {{
      "form": "<the exact word-form as given>",
      "def": "<concise English gloss(es), comma-separated if genuinely ambiguous>",
      "nl": "<the Modern Dutch equivalent word/spelling a fluent Dutch reader would recognise — e.g. Middle Dutch 'dorpren' -> 'dorpers/boeren', 1860-spelling 'myn' -> 'mijn', 'schryven' -> 'schrijven'. If the form IS already modern-spelling and needs no bridging, repeat it. Never leave empty.>",
      "lemma": "<the dictionary/citation form this word-form derives from>",
      "grammar": "<brief part-of-speech/grammatical note, e.g. 'n.', 'v.', 'adj.', 'conj.', 'adv.', 'pron.'>"
    }}>
  ]
}}

If you are not confident of a form's meaning, give your best defensible reading rather
than omitting it, but keep "def" honest and unpadded. Output the JSON object and nothing else."""


def tokenize(text_path: Path) -> list[str]:
    text = text_path.read_text(encoding="utf-8")
    # Split on whitespace and punctuation, keep letters (incl. accented) and internal hyphens/apostrophes.
    raw_words = re.findall(r"[^\W\d_]+(?:['’-][^\W\d_]+)*", text, flags=re.UNICODE)
    seen = {}
    for w in raw_words:
        key = w.lower()
        if key not in seen:
            seen[key] = w
    return list(seen.values())


def normalise_key(value: str) -> str:
    decomposed = unicodedata.normalize("NFD", value.lower())
    return "".join(ch for ch in decomposed if unicodedata.category(ch) != "Mn")


def call_model(prompt: str, timeout: int = 280):
    result = subprocess.run(
        ["python3", CONSULT, "--model", MODEL],
        input=prompt,
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip())
    raw = result.stdout.strip()
    if raw.startswith("```"):
        raw = raw.split("\n", 1)[1]
        if raw.rstrip().endswith("```"):
            raw = raw.rstrip()[:-3]
    return json.loads(raw.strip())


def build_job(job):
    words = tokenize(job["text_path"])
    print(f"{job['var_name']}: {len(words)} unique word-forms")
    entries = {}
    for i in range(0, len(words), BATCH_SIZE):
        batch = words[i : i + BATCH_SIZE]
        prompt = PROMPT_TEMPLATE.format(label=job["label"], words="\n".join(batch))
        data = call_model(prompt)
        for e in data.get("entries", []):
            key = normalise_key(e["form"])
            if not key:
                continue
            entries[key] = {
                "def": e.get("def", ""),
                "nl": e.get("nl", ""),
                "grammar": e.get("grammar", ""),
                "lemma": e.get("lemma", ""),
            }
        print(f"  batch {i // BATCH_SIZE + 1}: {len(batch)} words -> {len(entries)} entries so far")

    lines = [
        f"// AUTO-GENERATED by scripts/build_dutch_dictionaries.py via DeepSeek-V4.1-Flash. Do not edit manually.",
        f"// Scope: {job['label']} — only the word-forms in this specific import, not a general dictionary.",
        f"const {job['var_name']} = {{",
    ]
    for key in sorted(entries):
        e = entries[key]
        lines.append(f'  "{key}": {json.dumps(e, ensure_ascii=False)},')
    lines.append("};")
    job["out_path"].write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote {job['out_path'].relative_to(ROOT)} ({len(entries)} entries)")


if __name__ == "__main__":
    for job in JOBS:
        build_job(job)
