#!/usr/bin/env python3
"""Build an Old English lookup dictionary from the Beowulf thesaurus archive."""

from __future__ import annotations

import json
import re
import unicodedata
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ARCHIVE = Path("/Users/alexandermacmillan/Downloads/doi-10.34894-totfgz.zip")
OUTPUT = ROOT / "generated" / "imported-old-english-dictionary.js"


def strip_diacritics(value: str) -> str:
    decomposed = unicodedata.normalize("NFD", value)
    return "".join(ch for ch in decomposed if unicodedata.category(ch) != "Mn")


def normalise_key(value: str) -> str:
    return strip_diacritics(value.lower()).replace("’", "").replace("'", "")


def clean_gloss(entry: str, lemma: str) -> str:
    text = entry.replace("\n", " ").strip()
    text = re.sub(rf"^\s*{re.escape(lemma)}\s*,\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"^\s*[^,]+,\s*[^,]+,\s*", "", text)
    text = text.split(";", 1)[0].strip()
    text = text.split(".", 1)[0].strip()
    text = re.sub(r"\s+", " ", text)
    return text or "Old English word"


def main() -> int:
    if not ARCHIVE.exists():
        raise SystemExit(f"Missing archive: {ARCHIVE}")

    with zipfile.ZipFile(ARCHIVE) as zf:
        data = json.loads(zf.read("Beowulf_Thesaurus_1.0.json"))

    entries: dict[str, dict[str, str]] = {}
    for page_entries in data.values():
        for item in page_entries:
            lemma = str(item.get("lemma", "") or "").strip()
            entry = str(item.get("entry", "") or "").strip()
            pos = str(item.get("pos", "") or "").strip()
            if not lemma or not entry:
                continue
            key = normalise_key(lemma)
            gloss = clean_gloss(entry, lemma)
            grammar = pos.replace("  ", " ").strip()
            value = {
                "def": gloss,
                "grammar": grammar,
                "lemma": lemma,
            }
            if key not in entries or len(gloss) < len(entries[key]["def"]):
                entries[key] = value

            compact = normalise_key(strip_diacritics(lemma).replace(" ", ""))
            if compact and compact not in entries:
                entries[compact] = value

    payload = json.dumps(entries, ensure_ascii=False, indent=2, sort_keys=True)
    OUTPUT.write_text(
        "// AUTO-GENERATED by scripts/build_old_english_dictionary.py. Do not edit manually.\n"
        "// Source: Beowulf Thesaurus archive.\n\n"
        f"const OLD_ENGLISH_DICT = {payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT.relative_to(ROOT)} with {len(entries)} entries.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
